### ISSUE TITLE
Permanent owner change with multiple Hacker tanks

### ISSUE THREAD

**Issue by OcelotWalrus** [OpenHV/OpenHV#1023]
See https://discord.com/channels/840983316395720715/842332699459977218/1258478361173430293 for the video (it's too big for github).

**Comment by WilliamWeberBerrutti** [comment]
I have no access to Discord. Please post the replay file.

I also reported this issue on Matrix, but imho it's better to document them here.

**Comment by OcelotWalrus** [comment]
> I have no access to Discord. Please post the replay file.

Ain't you Cyantusk?

**Comment by OcelotWalrus** [comment]
Why do you say you've got no access to discord then?

**Comment by GraionDilach** [comment]
https://graiondilach.hu/other/2024-07-04_19-38-55-trimmed.mp4

**Comment by WilliamWeberBerrutti** [comment]
> Why do you say you've got no access to discord then?

It's because I have no Discord account, and I have no interest on creating one.

**Comment by Mailaender** [comment]
This is not a problem with the Deviator upstream because it uses a slow missile while we have a contionous zap.
