### ISSUE TITLE
Defense Panel positioning/hotkeys differ in skirmish and multiplayer

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1037]
![Screenshot_20240710_082611](https://github.com/OpenHV/OpenHV/assets/7718402/9c1298e0-a5b1-44b4-b676-d4258656c6be)

It may be confusing for players that they are in positions F1-F3 on human player matches and disabled when there are bot players, because all other buildings are shifted 3 positions, potentially messing with their muscle memory when using hotkeys on that tab. Maybe it should be better if walls and gates were on positions F7-F9?

**Comment by Mailaender** [comment]
The positioning is also about availability in the tech tree.

**Comment by OcelotWalrus** [comment]
Maybe that as @WilliamWeberBerrutti, to keep the hotkeys the same, instead of disabling the walls and making them disappear, they could just be put gray like when you don't have a prerequisite. This prerequisite would say "Disabled".
