### ISSUE TITLE
Make Main Base button always visible on the last position on the Building Panel

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1038]
![Screenshot_20240710_082506](https://github.com/OpenHV/OpenHV/assets/7718402/f9ceb049-d29d-46b7-bda6-a1a8944ce901) ![Screenshot_20240710_082545](https://github.com/OpenHV/OpenHV/assets/7718402/5ceeb42a-50ba-456e-9c03-e8859455929a)

Making it visible all times (not only when Outputs are built) may be more clear for players that may wish to understand when it's possible to rebuild Main Bases, and positioning it to always be the last building may be a better position for it to be (since it's used sporadically).

**Comment by OcelotWalrus** [comment]
I mean, it's in the encyclopedia.

**Comment by WilliamWeberBerrutti** [comment]
> I mean, it's in the encyclopedia.

Not everyone can (or want) read the entire Encyclopedia (which has a lot of information) to learn about the mechanics of the game. Some prefer to just play and learn by playing (like in my case).

**Comment by OcelotWalrus** [comment]
Plus, the builder's description says it allows base reconstruction. It's really not hidden in my opinion.

**Comment by WilliamWeberBerrutti** [comment]
> Plus, the builder's description says it allows base reconstruction. It's really not hidden in my opinion.

But it doesn't say where you can build it, on which tab. Having the icon on the Building tab always visible is more visual and clearer to understand, in my opinion.
