### ISSUE TITLE
Ore Smelters from both Factions incorrectly animate when severely damaged

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1104]

**Comment by OcelotWalrus** [comment]
What do you mean by "incorrectly animate"?

**Comment by OcelotWalrus** [comment]
Oh yeah I see what you mean. Gonna make a PR to fix that right now.

**Comment by OcelotWalrus** [comment]
That makes me have a question: should oresmelts be able to generate cash when heavily damaged?

**Comment by GraionDilach** [comment]
No structure loses it's gameplay effect due to damage.

**Comment by OcelotWalrus** [comment]
"No structure loses it's gameplay effect due to damage."?

**Comment by OcelotWalrus** [comment]
Oh you mean its.
