### ISSUE TITLE
Add a warning time/delay for the support powers.

### ISSUE THREAD

**Issue by Rampoina** [OpenHV/OpenHV#1112]
It would be nice if the support powers would give the player a warning before they hit so they have a bit of time to react:

- **Airstrike**: like other games the direction the planes are coming from could be shown to the player with lines.
- **Droppods**: the area the droppods are going to drop could be shown a few seconds before they do with a circle or something like that (as long as you have vision of that area)
- **Howitzer**: some kind of target could be shown where the howitzer is pointing at. (as long as you have vision)
- **Televator power**: the delay where the units are appearing but aren't targettable could be increased. (one really strong strategy is to teleport bomb pods/flamers directly on top of the base)

**Comment by OcelotWalrus** [comment]
I've been thinking of adding stuff similar to what you request here. We could simply delay a bit more the instant support powers (drop pods, televator power, railgun), and make so that every support power places a beacon where they're gonna strike, like in RA or D2K.

**Comment by OcelotWalrus** [comment]
I don't know how to indicate the direction of incoming bombers though.

**Comment by OcelotWalrus** [comment]
About indicating the direction of incoming bombers, maybe it shouldn't be indicated. It's nice to warn the player, but if you give him every bit of information, it's not very interesting. Similarly to how only powerful support powers' (nuke, railgun) timers are shown to everyone, but not the other ones (field, howitzer, droppods, airstrike, comlink etc...).

**Comment by Mailaender** [comment]
@OpenRA has a concept called `Beacon` but it is only shown to allies.

**Comment by OcelotWalrus** [comment]
Ooh shoot! Because the PR I made added beacons to very support power that's compatible with it, thinking it'd communicate the location to everyone.

**Comment by OcelotWalrus** [comment]
Mailaender I got a question: is there any solution to beacons, that'd work basically the same but would be displayed to every player? If not, would it be possible to change beacons to do so, with some boolean trait?

**Comment by Mailaender** [comment]
No, it is not possible and also not planned.

**Comment by WilliamWeberBerrutti** [comment]
Without some kind of delay / warning, support powers could be annoying for targetted players, specially for newcomers, and even imbalanced (for some). I think this should be a good QoL improvement to the game, even if it requires some work to be done.

**Comment by OcelotWalrus** [comment]
I still don't understand why #1116 was closed.
