### ISSUE TITLE
Add an `ActivationDelay` field to both DropPodsPower and TeleportPower

### ISSUE THREAD

**Issue by OcelotWalrus** [OpenHV/OpenHV#1115]

**Comment by OcelotWalrus** [comment]
If it's not too much asking Mailaender, would you mind adding that functionality to the engine this weekend or next one? One of my PR misses that functionality to be merged. I don't think it's too complicated to implement that if I'm right.

**Comment by Mailaender** [comment]
That would feel awkward. Support powers need to be instant.
