### ISSUE TITLE
Harbor LOS is missing explored cells at the bottom part

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1129]
![Screenshot_20240806_161037](https://github.com/user-attachments/assets/bd814638-9177-494c-84b8-74c4194b3083)

**Comment by GraionDilach** [comment]
> `Footprint: xxx x=x ___`

Only the x cells count for providing sight and that's why this happens. Notsure what to do here.

**Comment by WilliamWeberBerrutti** [comment]
What if the footprint is like this?

`Footprint: xxx xxx ___`

**NOTE:** I don't know what each character does

**Comment by GraionDilach** [comment]
> x means cell is blocked, capital X means blocked but not counting as targetable, = means part of the footprint but passable, _ means completely empty.

**Comment by Dzierzan** [comment]
And there's also "+" which means passable but an actor can't stay on it.

**Comment by GraionDilach** [comment]
Oh, yes... it just isn't mentioned in the tag description anywhere (Which is an upstream documentation issue).
