### ISSUE TITLE
Synapol's Missile Sub has no vision under shroud

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1132]
Having Drone Ship in comparison on the right:

![Screenshot_20240806_175723](https://github.com/user-attachments/assets/9b164c4f-8a9c-469d-8224-5cef82403f30)

Maybe both should have the same vision.

**Comment by OcelotWalrus** [comment]
I think that's just because it's underwater.

**Comment by Mailaender** [comment]
The `@Hacked` range is probably missing. It should not be zero only lower.
