### ISSUE TITLE
Speeders can land on Traders for no reason

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1138]
It wasn't damaged and also it doesn't refill the ammo. Maybe they shouldn't be allowed to land, like the Banshee. I don't think it needs ammo refill on Traders. Would be annoying.

![Screenshot](https://github.com/user-attachments/assets/8e18b9c8-aaf2-416c-8258-b2ec2c82df7b)

**Comment by OcelotWalrus** [comment]
That's the case for every plane. But it doesn't work with helicopter so it should be an easy fix.

**Comment by WilliamWeberBerrutti** [comment]
Also, I just noticed the shadows are too distant from the unit when it lands

**Comment by OcelotWalrus** [comment]
That's an issue with the engine. The auto-generated shadow are set to an offset to give more 3D impression (even if it's a 3D engine), but it doesn't take count of the height.

**Comment by WilliamWeberBerrutti** [comment]
Maybe it should be interesting to disable landing unless if the Trader can do something on the landed unit.

**Comment by OcelotWalrus** [comment]
Perhaps to upgrade them?
