### ISSUE TITLE
The capturing positions of the Technician seem irregular around the Drop Zone

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1166]
The distance to the right seems excessive:

![Screenshot_20240826_182732](https://github.com/user-attachments/assets/a05d361f-b3fa-480c-bb3d-e7545e46bacb)

And it seems he can't capture the structure touching the top and left borders, he must go all the way down:

![Screenshot_20240826_182838](https://github.com/user-attachments/assets/201e601d-8586-4a4e-8e91-3c67c62cf3a5)

**Comment by Mailaender** [comment]
This has technical reasons similar to the setup of the trade platform.
