### ISSUE TITLE
It's not possible to use DropPods on Ice Terrain

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1168]
![Screenshot_20240826_183948](https://github.com/user-attachments/assets/c8a208f0-a6ed-4b2f-9177-d8cb00ec8f82)

**Comment by OcelotWalrus** [comment]
Mailaender, seems that the allowed terrain is hard-coded. It shouldn't and there should be a `AllowedTerrain` tag for the `DropPodsPower` trait.
