### ISSUE TITLE
Terrain types limited to 32

### ISSUE THREAD

**Issue by OcelotWalrus** [OpenHV/OpenHV#1177]
"Terrain is handled everywhere as an array of strings, excluding Locomotor's MovementClass, because it's stored in a static unit, instead of a BitSet array to expand dynamically probably due to optimization. Not sure what to suggest to free up movement classes... maybe merging the ramps back."

**Comment by Mailaender** [comment]
This is an upstream problem: https://github.com/OpenRA/OpenRA/issues/21567
