### ISSUE TITLE
Critters block buildings

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#1182]
Critters do not go away when you place buildings on them. Maybe it should be interesting to make they do it? Thinking like in Age of Empires where this does happen if you place a building on a Deer or Boar

**Comment by Mailaender** [comment]
You can not order them as you are not its owner.

**Comment by WilliamWeberBerrutti** [comment]
I thought the same logic of https://github.com/OpenHV/OpenHV/issues/1178 could be applied here.

**Comment by Mailaender** [comment]
I currently don't plan of adding a zone of unbuildable space around all buildings.
