### ISSUE TITLE
Add land Super Units

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#1197]
Similar to the recently added Gunship and Battleship. Factories already have 2x2 pads so they can construct massive units without visual glitches.

**Comment by Mailaender** [comment]
They will glitch when they move on the cell-based grid.

**Comment by WilliamWeberBerrutti** [comment]
Maybe we don't need land super units (at least for now). We have to finish our asymmetry changes before evaluating it again I guess.
