### ISSUE TITLE
`Scientist Rescue` mission issues

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#1216]
User `xaxlhome` posted on Discord server two issues with Scientist Rescue mission:

> Hi, i found 2 problems in  Mission 3 "Scientist Rescue".
Its possible to put my troops in the heli, but can't get them out, so i needed to restart.
The Scientist is named civilian, it's confusing.

> PS:` its a nice mission.

**Comment by Dzierzan** [comment]
@OcelotWalrus

**Comment by OcelotWalrus** [comment]
About the troops being unable to unload: I don't know any way to allow them doing that, as the dropship's set to be uncontrollable by the player.

**Comment by Dzierzan** [comment]
Just reverse that, create an actor which can only load civilians.
