### ISSUE TITLE
Various inconsistencies between structure hitboxes, artwork size and targeting positions

### ISSUE THREAD

**Issue by GraionDilach** [OpenHV/OpenHV#132]
Something I noticed during setting up #126. There are multiple issues here.

Personally I'd propose that hitboxes should be aligned to cells and targeting offsets should be the center of cells with buildings. This is a step backwards compared to what OpenRA allows, but this would also ensure that customized offsets wouldn't provide edge cases in gameplay balance.

![image](https://user-images.githubusercontent.com/1136302/89712960-87813300-d994-11ea-817f-e217eafe8b4b.png)

**Comment by Mailaender** [comment]
That might be the reason why buildings take way too much damage.
