### ISSUE TITLE
OpenHV talk/workshop @ Kieler Open Source und Linux Tage Online?

### ISSUE THREAD

**Issue by m23project** [OpenHV/OpenHV#144]
Hi,

does anybody like to hold a talk or make a workshop about OpenHV during the Kieler Open Source und Linux Tage Online (18th + 19th of September 2020)?

More information at https://kieler-linuxtage.de/referenten-info .

Cu Hauke

**Comment by Mailaender** [comment]
I submitted a talk that will also cover https://github.com/OpenRA/OpenRA/issues/18507.

**Comment by Mailaender** [comment]
https://kieler-linuxtage.de/p/KOLT20#471
