### ISSUE TITLE
Bots will only shield one unit

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#150]
They can't apply the support power to a group of units.

**Comment by GraionDilach** [comment]
I've seen them shielding multiple units occasionally but I have used a completely different support power targeter mindset for stuff like these in AS mods. I can try porting that over.

**Comment by Mailaender** [comment]
That would be great. I had a look myself. https://github.com/AttacqueSuperior/ValiantShades/blob/master/mods/ra2vsh/rules/ai.yaml doesn't seem to support iron curtains. The chronosphere has a modified `OrderName` that I however can't find at https://github.com/AttacqueSuperior/Engine. https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/BotModules/SupportPowerExplicitTargetBotModule.cs looks interesting, but it also targets just one unit.

**Comment by GraionDilach** [comment]
https://github.com/AttacqueSuperior/ValiantShades/blob/aeaaefff3413f65fce8ef52130659c7287ca87bb/mods/ra2vsh/rules/attacheffects.yaml#L327-L342 ;)
