### ISSUE TITLE
Selling factories crashes the game

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#171]
> Actor factory3 has multiple traits of type `OpenRA.Mods.Common.Traits.Render.WithMakeAnimation`

**Comment by GraionDilach** [comment]
`Sellable->SkipMakeAnimation: true` can fix the crash but we also have visual glitches coming outright from `build-vanish` and whatnot. Might need to duplicate the entire logic downstream to accommodate our edge-cases.
