### ISSUE TITLE
Project proposal: recolor the blue light animations to red for Synaty Corp.

### ISSUE THREAD

**Issue by GraionDilach** [OpenHV/OpenHV#184]
The Spaceport sticks out currently, being the sole red lighted building among all of them. Having this change would help on visually differing the two faction from each other.

**Comment by Dzierzan** [comment]
So far progress:

![image](https://user-images.githubusercontent.com/17529329/142498294-f5dac3b9-b327-4c67-842e-51cb28fa1138.png)

**Comment by GraionDilach** [comment]
Think this is mostly done by now.

**Comment by Dzierzan** [comment]
Only SC Tech center is remaining. Generator was updated in the meanwhile:

![generator2](https://user-images.githubusercontent.com/17529329/143581731-520c05a6-f3d3-418f-a12c-996dc299d36c.gif)
