### ISSUE TITLE
Bots don't know how to use the mine layer

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#228]
https://github.com/OpenRA/OpenRA/issues/18266

**Comment by GraionDilach** [comment]
For this one I would probably rip a page out from Generals and just add specific waypoint actors to the maps where the AI should deploy the mine layers to. For the record, Generals AI is entirely running on fixed paths and doesn't do much pathfinding for strike teams.

**Comment by Mailaender** [comment]
I think something like the defense turret placement (somewhere in the direction toward the enemy) would be enough.

**Comment by Mailaender** [comment]
Thanks for sharing @dnqbob I added a slightly refactored version of https://github.com/OpenRA/OpenRA/pull/20574.

**Comment by Mailaender** [comment]
![Screenshot_20221222_171806](https://user-images.githubusercontent.com/756669/209217322-55c954eb-f889-482e-820d-423a0abb7433.png)

The only issue I saw is that when it gets infantry dropped it will start to mine its own base even production exits.

**Comment by dnqbob** [comment]
You can use "AwayFromAlliedTargetTypes" and "AwayFromCellDistance" to prevent this.
