### ISSUE TITLE
Harbor can be easily placed with all exits blocked

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#254]
Mostly an AI issue.

![image](https://user-images.githubusercontent.com/756669/115119823-a49de500-9faa-11eb-9fa3-a57e96827fd1.png)

**Comment by Dzierzan** [comment]
I believe OpenKrush has a special trait which allows units clip through if the exit is blocked.

**Comment by GraionDilach** [comment]
Exit priorities for this case are an engine property and don't require a custom trait.

**Comment by Mailaender** [comment]
![image](https://user-images.githubusercontent.com/756669/115300306-18cdb980-a160-11eb-9758-19d8fcb9a224.png)

The remaining problem is that at least 2 boats need to get stuck before the exit is changed.
