### ISSUE TITLE
Burnt trees require more tiles

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#288]
Currently only one tile exists for that.

**Comment by Mailaender** [comment]
Squashed ones as well.

**Comment by Dzierzan** [comment]
![treeashgrass](https://user-images.githubusercontent.com/17529329/134803118-756d5bfc-da7f-41da-9cd3-470cf6b6b9a5.png)
![treeashsnow](https://user-images.githubusercontent.com/17529329/134803121-8c032803-45d0-433f-be99-7ea2a12740a0.png)
