### ISSUE TITLE
Reconsider the resource gathering model.

### ISSUE THREAD

**Issue by GraionDilach** [OpenHV/OpenHV#29]
There are multiple concerns of mine here:
 - The current artwork for both iron and gold look wrong (random ingots on the map) and have very crude steppings with no proper difference between step 2 and step 3. This artwork is not suitable for resource deposits in line with the C&C harvesting logic. Also, steering away from C&C here is probably a good thing.
 - Hard Vacuum was intended to use a similar model of resource gathering as Warcraft 2 oils used - there is a spot marked on the field where the player built a mine on and then mined it out. Sure, this might not be possible currently within OpenRA (the closest thing I can think of doing this would be the Holloweye-WW1 Trader logic).

My best suggestion currently is to reuse the HV mine artwork for capturable and immune oil derricks (which transfer back to neutral when their owner dies) until there is a clear idea/direction for the resource gathering.

**Comment by Mailaender** [comment]
The current setup is just a placeholder. We will probably go with something similar to https://github.com/IceReaper/KKnD/tree/master/OpenRA.Mods.Kknd/Traits/Resources

**Comment by Dzierzan** [comment]
There's that miner unit which has transformation animation. If it's all about getting oil then everything you already have. IceReaper made such logic for KKND's resource system.

**Comment by GraionDilach** [comment]
If there would be a dummy DLL to expand on, I guess I can take a look into that. There are some artwork aspects I'd give a try to anyway which will need code from AS to be able to function.
