### ISSUE TITLE
Resource managment

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#290]
Alright, this is more like a debate than an issue, but I would love to talk about this.

Currently resources in OpenHV are limitless. You just deploy your Miner and get an infinite stream of money. IMO there should be something more than that. In RTS games you usually have to expand as resources near your area can be depleted after some time. Of course in CnC games, ore/tiberian deposits regrow after some time, but this tempo is slow as it should be.

What I have in mind is also about depleting resources. But! The main difference would be that the resource deposit never goes fully depleted, just produces less money over time.

After deploying the miner:
- 0 - 5 mins = 100% of income
- 5 - 10 mins = 75% of income
- 10 - 15 mins = 50% of income
- 15 - 20 mins = 25% of income

There should be also an indicator, like a bar which shows how much the deposit is depleted.

**Comment by GraionDilach** [comment]
The problem I see with this - note I haven't played with the game for a great while now - is that the UI needs a function for map editors to tweak this length if they desire.

My reasoning comes from Red Alert 3, where each mine had a fixed amount of ore and after that initial value emptied out, each carry still delivered like 10% or so. (which is fairly similar to this one here).

I wouldn't tie this to minutes either but to a (fixed?) amount of deliveries for each stage.

Keep also in mind that you can easily end up with a stalling game after a mapwide exhaustion if there aren't enough gameplay opportunities to turn a tide decisively. If floating is what causes stalling in OpenHV today then this might not be fixing the problem, but increasing it's severity.

**Comment by Dzierzan** [comment]
It can be the amount of deliveries as well.

The thing is, I would also like to create a special building which generates money. Think of Black Market in Generals. So in the late game, players would have an alternative way to get money.

There are also now tech miner buildings which work just like CnC tech drill rigs.
