### ISSUE TITLE
DotNET messages during build

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#326]
I have built the project using Mono last version downloaded from official repositoriers ( https://mono-project.com/ ) but, during building I got the following messages repeated:

```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed dotnet SDKs
```

I think it is because some of the instructions given in the `Makefile` are specific of DotNET and are recognized by the tools.

Since Mono is not deprecated itself, I would like to ask if this could be fixed in some way.

**Comment by Mailaender** [comment]
Did you run it with the parameter `make RUNTIME=mono`?

**Comment by Mailaender** [comment]
> Did you mean to run dotnet SDK commands? Please install dotnetsdk

Seems to be displayed if you have the .NET runtime installed, but not the SDK.

**Comment by EchedeyLR** [comment]
> Did you run it with the parameter `make RUNTIME=mono`?

Yes. And no, I only have Mono.

**Comment by Mailaender** [comment]
https://devblogs.microsoft.com/dotnet/introducing-net-5/ has already integrated some parts of Mono. If you want to develop OpenHV or any @OpenRA game you will need to https://aka.ms/dotnet-download now or in the near future. I know that this hurts, as only few Linux distributions package .NET Core and its circular dependencies make it difficult to package.

**Comment by EchedeyLR** [comment]
AFAIK DotNET build from source is still being worked in a Microsoft repository as it is not possible by now.

**Comment by Mailaender** [comment]
There is https://fedoraproject.org/wiki/DotNet but I didn't even try to reproduce it for @openSUSE as it looks like pain. Even https://aur.archlinux.org/ seems to just take the binaries from @Microsoft and install those.

**Comment by EchedeyLR** [comment]
Thank you for the reply.
