### ISSUE TITLE
Game is still listed in the Lobby/Masterserver after leaving it

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#327]
I created a game in the Lobby (forwarded the port, etc) which got registered and worked successfully. 

However, after leaving/closing it, the game was still registered even after restarting the game and refreshing. A friend also confirmed that was still registered in the Lobby or the Masterserver after connecting for first time when I closed the game even after refreshing.

![snapshot47](https://user-images.githubusercontent.com/56733813/130339917-2d34ef2b-64ce-441c-b21d-b002f3fe4094.png)

I don't know if the issue is set with OpenHV or OpenRA Masterserver itself.

Edited:

The game took around 5-10 minutes to disappear after refreshing at any moment.

A friend could reproduce the issue correctly just creating their own game with an AI and closing it.

![snapshot48](https://user-images.githubusercontent.com/56733813/130340125-633a7f5d-8ca5-44f8-be79-71380cdc4ad3.png)

After they re-created the game, that "old" game state seemed to disappear correctly and got set to the new game state without duplicating the vew as if there were two games.

![snapshot49](https://user-images.githubusercontent.com/56733813/130340160-41bd9137-f5cc-440b-a51a-5137038b8e12.png)

Edited 2:

We both are using the GNU/Linux AppImage of the [20210517 pre-release](https://github.com/OpenHV/OpenHV/releases/tag/20210517).

Don't believe I am using WoeXP ;-)

**Comment by Mailaender** [comment]
The game will take exactly 5 minutes to disappear. https://github.com/OpenRA/OpenRAMasterServer/blob/e1370bd99db2b8dc3b84ca689ae0c162cde5ee3d/config.php#L7 
I don't think this is a bug and I don't plan to fork the master server.

**Comment by Mailaender** [comment]
Some background why this is 5 minutes: https://www.openra.net/games/ has ~300 servers. Most of them are always on dedicated machines. If they would all ping every X second just to stay listed, the master server will get stressed. So close your games properly if you don't want to spam the master server with invalid entries.

**Comment by EchedeyLR** [comment]
Thank you for the explanation.

**Comment by Mailaender** [comment]
Actually, I tested this and changed my mind. You are right: pressing leave does not update the master server list as expected. I thought you did just ALT + F4 out of the game. https://github.com/OpenRA/OpenRA/pull/19627 should fix this.

**Comment by EchedeyLR** [comment]
> Actually, I tested this and changed my mind. You are right: pressing leave does not update the master server list as expected. I thought you did just ALT + F4 out of the game. [OpenRA/OpenRA#19627](https://github.com/OpenRA/OpenRA/pull/19627) should fix this.

Oh sorry, next time I will be clean while writing to avoid misunderstanding.
