### ISSUE TITLE
Change default game name

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#328]
In 0 A.D., the default game name is `$USERNAME's game` where `$USERNAME` is the username set by the user in the multiplayer account.

I think that OpenHV could do the same using the player name set by the user in the settings.

Edited:

I am aware that the game name is set to a new default when I edit it a first time.

**Comment by Mailaender** [comment]
Depends on https://github.com/OpenRA/OpenRA/pull/19626.
