### ISSUE TITLE
Possibility to create the AppImage with Mono runtime

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#330]
It would be great if embedding Mono runtime was also possible instead of DotNET.

**Comment by EchedeyLR** [comment]
Sorry, I just followed the Wiki in the `Build` section.

https://github.com/OpenHV/OpenHV/tree/master/packaging solves my issue.

**Comment by EchedeyLR** [comment]
I checked that is only possible packaging with DotNET.

**Comment by Mailaender** [comment]
Won't fix because Mono is deprecated. The default runtime is .NET 5.

**Comment by EchedeyLR** [comment]
Where is set that Mono is deprecated?

Development website of Mono, the last released during these years after acquired by Microsoft and their about webpages don't set that.

**Comment by Mailaender** [comment]
It was deprecated by @OpenRA at least. The plan was to make .NET Core binaries on @Mono, but that didn't happen (yet).

**Comment by EchedeyLR** [comment]
Thank you for the explanation.

What I read in the Mono project section about DotNET integration is that, as standalone project they wanted to integrate faulty functionality from .NET Core since this is FLOSS and Mono will provide some source code portability to DotNET and similar parts.

But they don't set nothing about merging or dissapearing. This is all from separated projects perspective.

**Comment by Mailaender** [comment]
I thought @mono was to be integrated into @dotnet. https://www.mono-project.com/docs/about-mono/releases/ also seemed to have stalled, but I am not really an expert. This is using the https://github.com/OpenRA/OpenRAModSDK scripts for packaging anyway with only minor changes.

**Comment by EchedeyLR** [comment]
I read https://www.mono-project.com/docs/about-mono/dotnet-integration/ section.

**Comment by Mailaender** [comment]
https://github.com/mono/website/blob/gh-pages/docs/about-mono/dotnet-integration.md is from 2014 and was last updated 2018.

**Comment by EchedeyLR** [comment]
You are right, however, since the webpage is informational and given the activity of Mono organization, I think that there is no reason to change it but I am only guessing, that is right.
