### ISSUE TITLE
Preferred colour button preview is not updated

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#333]
This only happens the first time you open the game.

It asks you for basic configuration and one of them is your preferred colour for the units but, even if the preview in the unit is correct when you select it to change it and save it with "store", it is not showed in the button preview.

This doesn't happen if you do that later in the settings menu.

**Comment by Mailaender** [comment]
Indeed. This will be fixed by https://github.com/OpenRA/OpenRA/pull/19631.
