### ISSUE TITLE
Add icon to the game for both itself and the windows one

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#336]
I think this could be more related to #329 but, the motivation for this is also that a friend using GNOME saw that the notification from GNOME about that the game is "prepared" (usual for any application that takes a bit to open and its window is deployed in background) showed no icon for it.

If I remember correctly, this is related to game icon for its execution (maybe referenced in an internal .desktop file inside the AppImage) and not the window icon.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/19528 got rejected but https://github.com/OpenRA/OpenRA/pull/19553 was integrated so I assume this will be fixed in the next release for @GNOME as well.

**Comment by EchedeyLR** [comment]
How this affect to users with other DE not based on current KDE or GNOME versions?

For example, I use TDE which was forked from KDE 3.5 in that era and now is like MATE for GNOME.
