### ISSUE TITLE
Clarify attribution with an explicit futureproof crediting guideline/standard to satisfy CC-BY requirements with an OS mindset.

### ISSUE THREAD

**Issue by GraionDilach** [OpenHV/OpenHV#4]
The CC-BY license is a good choice for the assets for this project. And as long as there is only a single artist whose assets are involved, a generic crediting message is enough.

The problem comes in if multiple additional artists starts contributing and/or people would start derivative works of the assets within the project, for example recoloring/remixing tiles to extend the tileset. There should be a way to effectively maintain who was the artist of a particular asset but maintaining this shouldn't happen within the ingame credits list because that would overload the widget.

A suggestion I can think of is to have a readme.md in every subfolder within bits where actual assets are which holds this information of ownership for each file (either separately, either with wildcards) and then demand outside asset contributions to include this information within their PR. This then allows for outside derived works to maintain the attribution required by the license and does not force them to fall back to a generic crediting and/or resulting with unclear or confusing licensing while also contributors can be ensured that their work does not get misattributed in the future either.

I know I can be a bit of annoyance with such an issue like above in the project's early state and i don't want to sound demanding so feel free rejecting it if you're thinking otherwise.

**Comment by Mailaender** [comment]
We may be able to auto-generate this from git where it is self-documented already.

```bash
git log --name-status --diff-filter=A --format='> %aN' \
| awk '/^>/ {tagline=$0}
       /^A\t/ {print tagline "\t" $0}'
```
