### ISSUE TITLE
Water/Lava flow

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#410]
> Deformable terrain with flowing water and lava

was mentioned in the [original design documents](https://lostgarden.home.blog/2005/03/27/game-post-mortem-hard-vacuum/).

Some experiments were done by adding them as a resource layer:

https://github.com/OpenHV/OpenHV/blob/80de1e435ebf78e0d10ee040dd669eb9aed473a7/OpenRA.Mods.HV/Traits/World/LiquidTerrainRenderer.cs#L18-L19

https://user-images.githubusercontent.com/756669/137640545-6a58a53a-3e9c-4742-a280-ffaaf6e57378.mp4

**Comment by nmoskopp** [comment]
How is this feature used in maps?

**Comment by Mailaender** [comment]
You place the water flow actor :wavy_dash: with the map editor.

**Comment by nmoskopp** [comment]
> You place the water flow actor wavy_dash with the map editor.

I think I did just that, but it did not seem to turn any tiles into water tiles.

Even if it did, I do not know which destroyable tiles can block water flow.

Am I supposed to use walls to block water?

**Comment by Mailaender** [comment]
As mentioned above, this was a quick experiment, not a finished feature. I had a mission in mind where a broken dam floods a river basin. However, I never got to script it as so many other requests piled up.
