### ISSUE TITLE
Wrong purple color range?

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#454]
I've noticed long time ago that there's something wrong with the purple color in game, it feels washed out. So I took a screenshot and compared it with the raw sprite. The result is below. @Mailaender are you sure you are using correct palette? I believe Daniel Cook created several palettes, for example snow trees have a bit different color range and I do believe I've seen palette with washed out purple colors as well.

![purple](https://user-images.githubusercontent.com/17529329/143490459-aaff05dd-a6aa-402b-91ee-58ea46a7b629.gif)

**Comment by Mailaender** [comment]
I copied the complete palette from one of the motherships.
