### ISSUE TITLE
Two notifications play at the same time when Droppod power is used

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#471]
@Mailaender you added once `reinforcements_have_arrived` quote for Droppod power and I later added `droppod_charging` for them. I didn't realize both quotes will play at the same time when support power is used. Yes, it happens without debug mode.

So either we get rid of `reinforcements_have_arrived` or `droppod_charging` (and for airstrike too to be consistent if you choose the latter option).

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/19667 already gave us non overlapping notifications.

**Comment by Dzierzan** [comment]
I mean those two notification according to the code will play at the same time. So one has to go.
