### ISSUE TITLE
Miner tower no longer fits ground resource deposit

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#496]
Some maps were made for the "old" setup of Miner tower. Now it doesn't fit ground around resource deposit.

![image](https://user-images.githubusercontent.com/17529329/147873099-7c29695e-2ece-4421-884f-c8367b5883cc.png)

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/commit/f42833ba58c3179f61751c56dc99d4b2480fc3fc solved it the other way round.
