### ISSUE TITLE
Greener pastures

### ISSUE THREAD

**Issue by Rampoina** [OpenHV/OpenHV#506]
It would be nice to have a few tiles of the rocky type be a bit less rocky, maybe with some patches of grass, a bush etc
It would allow making nicer dirt roads like this:

![2022-01-09-135157_870x692_scrot](https://user-images.githubusercontent.com/5653911/148682976-b5ffee90-b714-4bee-a81d-ae14379adbe0.png)

**Comment by Mailaender** [comment]
See https://github.com/OpenHV/OpenHV/pull/556
