### ISSUE TITLE
[Suggestion] Tutorial

### ISSUE THREAD

**Issue by ivanhrabcak** [OpenHV/OpenHV#507]
The game is pretty complex and is's missing a tutorial. I wanted to play it, but I was confused what the buildings do, how to progress, how to do anything really.

**Comment by Dzierzan** [comment]
First two missions are technically speaking the tutorial. Have you tried them?

**Comment by ivanhrabcak** [comment]
Yes I have played them now you are right! Sorry for wasting your time:(
