### ISSUE TITLE
AI vulnerable to rushes

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#552]
The Rogue AI is vulnerable to rushes, including air. For air rush, it doesn't react, unless if the units get close to the defenses.

**Comment by dnqbob** [comment]
You can force AI to build barrack by using condition

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/issues/629 and https://github.com/OpenHV/OpenHV/issues/627 should lessen this.
