### ISSUE TITLE
Newbies can block resource deposits with buildings

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#553]
1. Make the right cell of the Resource Deposits unbuildable so people (specially beginners) don't block the Mining Tower construction accidentally with buildings
2. What if the Mining Tower requires 1 cell of space? How it'll affect balance? And how balanced is the 2 cell of space?
3. ~~Make it possible to (re)build the Main Base, maybe the same way as OpenRA? Or maybe limit to 1 Main Base and let the Main Base Vehicle be built only if the Main Base Building is destroyed? Or maybe the Main Base Vehicle spawns after some time, like if it was a special ability? The way it is now makes players vulnerable to focused attacks on the Main Base, giving too much advantage for the opponentes.~~

**Comment by GraionDilach** [comment]
3. is already resolved with https://github.com/OpenHV/OpenHV/commit/8af635e92eb3d747012a6e842f0c06b299c74a67 and followups.

**Comment by WilliamWeberBerrutti** [comment]
This situation returned to happen. This issue should be reopened.
