### ISSUE TITLE
Please update version flathub

### ISSUE THREAD

**Issue by Krasul1a** [OpenHV/OpenHV#592]
Please update version in https://flathub.org/apps/details/io.github.openhv.OpenHV

**Comment by Krasul1a** [comment]
Don't work multiplayer in version flathub. Sorry my English not very well.

**Comment by Mailaender** [comment]
I actually did https://github.com/flathub/io.github.openhv.OpenHV/commit/e07cda61ae44c7c843d96d9f605995df796f96f6 looks like the builder had connection problems.
