### ISSUE TITLE
Saved game from OpenHV 20220918 not visible in OpenHV 20221030

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#606]
I found out that the save games are saved per version of the game. Therefore I assumed some incompatibility that might prevent loading an older game. Yet, after I copied a saved game file from `$HOME/.config/openra/Saves/hv/20220918` to `$HOME/.config/openra/Saves/hv/20221030` it showed up and OpenHV was able to load it.

I suggest to show saved games regardless of the version of the game.

**Comment by Mailaender** [comment]
They are incompatible because saved games are in fact :fast_forward: replays. https://github.com/OpenRA/OpenRA/issues/18255

**Comment by nmoskopp** [comment]
I understand. Does this mean loading an older save game will not work reliably (i.e. it may work or not) or will it always lead to a corrupted game state?

**Comment by Mailaender** [comment]
When the rules change (significantly) you get a desync crash.
