### ISSUE TITLE
Miner bought with a trade platform spawns either at main base or not at all

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#610]
A miner bought with a trade platform while having a main base spawns it at the main base instead of the trade platform.

A miner bought with a trade platform while not having a main base does not spawn at all after construction is finished.

I suggest to spawn the miner at the trade platform in any case, as this greatly simplifies the mental model.

**Comment by Mailaender** [comment]
I can't reproduce this problem:

**Comment by nmoskopp** [comment]
I have no idea what the difference is between your setup and mine, but I can consistently reproduce the case where I sold my main base, but no miner appears when I use the trade platform to buy one.

I even have a replay, which I will upload after reporting yet another crash.

**Comment by nmoskopp** [comment]
Given https://github.com/OpenHV/OpenHV/commit/ee06ebb337186864be02ff6201a05f82f18cfdc0 … do you still need that replay?

Also I think this should be relabeled to bug.
