### ISSUE TITLE
Miner bought with vehicle factory either spawns at main base or not at all

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#611]
A miner bought with a vehicle factory while having a main base spawns it at the main base instead of the vehicle factory.

A miner bought with a vehicle factory while not having a main base does not spawn at all after construction is finished.

I suggest to spawn the miner at the vehicle factory in any case, as this greatly simplifies the mental model.

**Comment by nmoskopp** [comment]
Note that this issue is related to, but not a duplicate of https://github.com/OpenHV/OpenHV/issues/610 – a fix for one of them might address one or both of them.

**Comment by Mailaender** [comment]
You didn't buy the miner with the vehicle factory, but with the main base. It is just in the same build palette queue to save some space in the UI.

**Comment by nmoskopp** [comment]
> You didn't buy the miner with the vehicle factory, but with the main base. It is just in the same build palette queue to save some space in the UI.

Please explain: How can I buy a miner with the main base if I do not actually have a main base?

**Comment by Mailaender** [comment]
I see. That is indeed not the wanted behavior. The rest actually is. You can try to work with the build queues in the game rules. You will see that it is fiddly to get right. I won't add dramatic changes right before a stable release.

**Comment by Mailaender** [comment]
> Please explain: How can I buy a miner with the main base if I do not actually have a main base?

You hopefully have an outpost, which can build a main base which gives you back access to miner production.
