### ISSUE TITLE
Trade platform mechanic should be rebalanced

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#612]
The trade platform seems almost useless for vehicle production, as vehicles bought with it are both more expensive and take much longer to appear than using the vehicle factory. At minimum, buying vehicles using a trade platform seems about 10% more expensive and takes about 3 to 4 times as long to spawn the vehicle.

Examples for vehicle factory and trade platform price and construction/delivery duration:
* Assault Tank: 850$ & 16s vs 943$ & 48s
* Mobile AA: 500$ & 9s vs. 595$ & 31s
* Repair Vehicle: 800$ & 15s vs. 904$ & 46s

To make the trade platform a building that is not only constructed for repair and tech tree reasons, I suggest to make it better than the vehicle factory in a way that makes players evaluate which building they want to ~build first and/or~ use depending on the current game state – currently, players almost always prefer the vehicle factory, as getting vehicles with it seems both cheaper and much faster.

Suggestions:
* Keep the delivery times, but add a variable discount that makes bought vehicles cheaper. Dune 2000 does this AFAIK.
* Keep the pricing, but speed up the delivery time. This is unlikely to meaningfully change gameplay for the better, as the vehicle factory already spawns vehicles very fast.
* Keep both pricing and delivery times, but allow concurrent vehicle orders. Caveat: This could affect balancing a lot.
* Make it possible to buy special units using the trade platform that players can not get otherwise.

**Comment by nmoskopp** [comment]
Quote https://forum.dune2k.com/topic/27611-starport-varied-cost-logic/?do=findComment&comment=394826

> In Dune 2000 the variation of the costs it's a 25%, and changes every minute (1500 ticks). However the units never cost more than the original production, so the 25% it's the maximum discount. A Combat tank (700 credits) will cost at his lowest 525 credits.

**Comment by nmoskopp** [comment]
Related OpenRA issue (bulk purchasing): https://github.com/OpenRA/OpenRA/issues/7055

**Comment by Mailaender** [comment]
Dune 2000 gameplay is very spammy.

**Comment by nmoskopp** [comment]
> Dune 2000 gameplay is very spammy.

Elaborate please. Do you mean lots of units are spawned?

**Comment by Mailaender** [comment]
Too many units are on the battlefield in late game.

**Comment by nmoskopp** [comment]
> Trade Platform is massively cheap powerwise compared to the Vehicles Factory (30 vs 150)

Little tension there, since a player needs a factory before they can build a trade platform.
