### ISSUE TITLE
Firefighting units should move closer to fire if given aggressive stance

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#616]
Currently, a firefighting unit might fight a fire but does not follow its spread.

I assume this happens since the fire is not moving around but spawning new fires.

Suggestion: If given “attack anything” stance, make firefighting units move closer to a fire than otherwise.

Could other units benefit from moving closer if given ”attack anything” stance so they can more easily rout a retreating foe?

**Comment by Mailaender** [comment]
I think https://github.com/OpenRA/OpenRA/pull/20257 is related to this.
