### ISSUE TITLE
Shutting down power to buildings makes them not count for the tech tree

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#620]
When I shut down power to my only vehicle factory, I can not build a trading platform.

This seems a bit weird, since a vehicle factory without power is still a vehicle factory.

**Comment by GraionDilach** [comment]
The other option would mean that structures which only have the passive effect of progressing on the tech tree would be built and immediately powered off - seen in OpenRA-RA and WW-TS meta. This was the least abusable while still consistent solution without making powerdown arbitrarily restricted to selected buildings.

**Comment by nmoskopp** [comment]
That makes sense indeed. What is WW-TS?

**Comment by GraionDilach** [comment]
Westwood iteration of TS. OpenRA already has a TS iteration on it's tree whose powerdown state I don't remember atm.

**Comment by Mailaender** [comment]
I already implemented it https://github.com/OpenRA/OpenRA/issues/3769 but must have forgotten to set it up here.
