### ISSUE TITLE
Add fighting to shellmap

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#621]
Other OpenRA games have a shellmap that shows fighting. OpenHV does not have this yet.

I tried adding actors to the shellmap, but they would not fight. Any idea why that is the case?

**Comment by Mailaender** [comment]
You have to script them with Lua.

**Comment by SeanScherer** [comment]
I'm not sure if there might be more to it ? (but my issue might well be a more generic one):

I made the shellmap playable (for testing purposes), and when playing, the turrets won't shoot. (I ended up removing and "re"-placing them via a lua map script as a workaround).

Hope that might help!

**Comment by Dzierzan** [comment]
One of our contributors is making a new shellmap. Once done, lua script needs to be injected if we want some fight on screen. Not an easy task as it depends what you want to happen on screen. On the other hand, simple skimish AI can be injected too. Needless to say it's someone I will do once the new shell map is done.

**Comment by nmoskopp** [comment]
Is Skirmish AI broadly predictable? If so, choreographing a full fight might be unnecessary.

**Comment by Mailaender** [comment]
> Is Skirmish AI broadly predictable?

No, it adds a lot of randomness to make skirmish interesting.

**Comment by Dzierzan** [comment]
Better shellmap was uploaded. I guess I will experiment with hacky AI for that as soon as I have time and motivation ^^.

**Comment by Mailaender** [comment]
The updated shellmap works fine even without active engagements. It shows a calm before the storm.

**Comment by nmoskopp** [comment]
> The updated shellmap works fine even without active engagements. It shows a calm before the storm.

I agree. I see the poetic simplicity – anticipating a fight is, after all, what players do in the main menu.

The kind of vibe you seem to desire could probably be enhanced by adding a drop zone to each base and/or adding some rudimentary AI that issues unit build orders. That way, units can mass in the main menu and you get a bit more movement that is not just creeps or resource transporters moving around.
