### ISSUE TITLE
Lack of air-to-air combat

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#622]
I have encountered situations in which two or more sides had air fleets that were not able to fight each other. Both air fleets engaged ground units and buildings, but were not able to fight each other. My last game like this turned into a game of bombing each others base fast enough to win.

**Comment by nmoskopp** [comment]
IMO this also makes elite pod spam much more viable than it should be (spamming a single unit should rarely be the correct tactic).

**Comment by nmoskopp** [comment]
> This is again on purpose as dog fights between planes and helicopters and planes don't work well.

Do you mean visually or gameplay-wise?

**Comment by nmoskopp** [comment]
Suggestion: Give air-based transport units (helicopter & dropship) AA capability.

**Comment by Dzierzan** [comment]
Yeah, we had this talk about air-air on Discord server. I am not sure if giving air-air to transport units would be a good idea either.

Of course "the lazy way" would be giving basic heli and plane air-air capabilities. If I were to do it, I'd spice this up somehow.

Another solution would be giving special assymetrical air units, something like in Starcraft game where each faction has own air-air unit which works differently. Of course that solution would require new artwork. I don't mind making new sprites, but at the same time I believe OpenHV has already too many units (it used to have even more).

**Comment by nmoskopp** [comment]
> Of course "the lazy way" would be giving basic heli and plane air-air capabilities. If I were to do it, I'd spice this up somehow.

Doing that does not seem like a good idea to me – it would mean that players who are building air units can likely disregard both mobile and fixed AA at no additional cost. It would also make advanced air units much worse.

**Comment by nmoskopp** [comment]
I realized that the lack of air-to-air combat also means that UFOs and hot air balloons can basically idle forever above/behind terrain impassable for ground-based anti-air units, which is a huge boost for artillery and missile submarines in the late game.

AFAIK late game elite pod spam still seems to be a hard-to-counter tactic in OpenHV 20221119.

**Comment by Mailaender** [comment]
I agree that the elite pod needs a nerf, though.

**Comment by nmoskopp** [comment]
> I agree that the elite pod needs a nerf, though.

I am not sure how you can nerf existing elite pods in a way that massing them to overwhelm air defenses is no a longer viable tactic.

I do have a suggestion though: What if elite pods became the dogfighting air superiority unit, with negligible or no damage against units and buildings (except against pods)? Tech-tree wise they fit the role as they appear late enough in the game and as long as they are slower than basic or advanced air-to-ground attack units, it should be possible to outrun them.
