### ISSUE TITLE
Rogue AI builds multiple radars in early game

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#624]
While other buildings provide a tangible benefit in multiples (e.g. production time reduction), radar only provides redundancy.

![hv-2022-11-02T111331545Z](https://user-images.githubusercontent.com/22373642/199476565-0650d3e2-5518-4fb4-aef5-8c2801bb71ec.png)

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/14024#issuecomment-913009649

**Comment by Mailaender** [comment]
This should be lessened or fixed by https://github.com/OpenHV/OpenHV/pull/800 and https://github.com/OpenHV/OpenHV/commit/c529ba07ae3ae5dac13699fdc809bb5f7d03ba77.
