### ISSUE TITLE
Cube Hunter AI sometimes ignores cubes

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#626]
Two tanks on the left are very close to a cube. However, they were not ordered to collect it in the game.

![hv-2022-11-02T112728654Z](https://user-images.githubusercontent.com/22373642/199478608-2723a22e-64e5-4539-84f1-ddc9278ca35c.png)

**Comment by nmoskopp** [comment]
The tank at the top left of the screenshot eventually collected the cube. Could it be that Cube Hunter AI only sends a single unit after a cube?

**Comment by Mailaender** [comment]
The search for cubes is throttled as pathfinding is expensive.

**Comment by nmoskopp** [comment]
> The search for cubes is throttled as pathfinding is expensive.

Please elaborate. How often does Rogue AI look for new cubes?
