### ISSUE TITLE
Rogue AI does not build much air defense

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#629]
This makes it easy to defeat a Rogue AI using air units, even for another Rogue AI. The screenshot shows the result of this happening in the bottom left base. The top right base was later attacked in the same way.

![hv-2022-11-02T114647276Z](https://user-images.githubusercontent.com/22373642/199482534-71870195-3f6c-4e08-accf-b971238e7e96.png)

**Comment by Dzierzan** [comment]
Hmmm... I am not sure, but I don't recall giving AI any orders for responding to air threat. AI builts turrets randomly. As a matter of fact, it builds everything randomly, so sometimes you see more X turrets, sometimes more Y turrets.
