### ISSUE TITLE
Rogue AI often does not use charged support powers

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#630]
4 Rogue AIs not using force field:
![hv-2022-11-02T113820271Z](https://user-images.githubusercontent.com/22373642/199483556-296db2d4-735f-4bb8-bccf-f37c14bdad7d.png)

2 Rogue AIs not using drop pods:
![hv-2022-11-02T114557672Z](https://user-images.githubusercontent.com/22373642/199483077-922171be-02d6-4d4d-a726-b5f2994a0949.png)

**Comment by Mailaender** [comment]
Do you mean they never use them?

**Comment by nmoskopp** [comment]
I think they eventually use them after some time, but in the meantime they hold back even if it would immediately benefit them in combat.

**Comment by Mailaender** [comment]
Try enabling the bot debug messages to gain some insight in their decision making.

**Comment by Mailaender** [comment]
In the advanced settings.
