### ISSUE TITLE
When told to force-attack their own position, some units instead go left until they hit an obstacle

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#634]
At least rocket pod, tank, stealth tank do the above.

Compare and contrast: Artillery will move away and shoot at the position.

**Comment by nmoskopp** [comment]
Could this be because tanks etc. attack units (that they track when they move) while artillery attacks positions?

**Comment by Mailaender** [comment]
I think it has something to do with the minimum range of the warheads. If this didn't happen in early releases, it might be related to recent pathfinder changes.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/16023

**Comment by Mailaender** [comment]
This was fixed in https://github.com/OpenRA/OpenRA/pull/20369.
