### ISSUE TITLE
Automatically power down radars a few seconds after entering low power state

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#637]
Radars do not work anyway in low power and powering them down might restore power in an emergency.

This change would remove a common source of useless busywork.

**Comment by Mailaender** [comment]
The AI will do this https://github.com/OpenHV/OpenHV/commit/9a82dc28d0691f8d6bd6bf2e3ea804f7d1b8f03a yet I won't automatize gameplay. Also, this will disable tech https://github.com/OpenHV/OpenHV/commit/4a1456f6e71447dc5e6dec5b5e506ea409746d9b and might even abort a build of a unit.

**Comment by nmoskopp** [comment]
> yet I won't automatize gameplay

Since this such statements have come up repeatedly regarding automation – I might not have understand what exactly constitutes gameplay in an RTS. Do you explicitly intend for OpenHV to have a gameplay in which both meaningful tactical choices (build order, which units do what) and fast reactions (power down radar when hearing low power warning) play a role? If so, is the latter some kind of minigame? Do you have some kind of design document that explains the reasoning? I would like to not waste time on issues that do not align with the vision.

**Comment by Mailaender** [comment]
Again, I urge you to join the chat before bombarding us with issues. There are no guidelines in place, there is no design document except maybe https://lostgarden.home.blog/2005/03/27/game-post-mortem-hard-vacuum/ upon which this is loosely based.
