### ISSUE TITLE
Rogue AI blocks off its own access to terrain and resources with buildings

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#640]
Top left: Existing resource transport route blocked.
Bottom right: AI player can not get to resources.

![hv-2022-11-06T125256772Z](https://user-images.githubusercontent.com/22373642/200171991-29d5dc61-4294-4cbf-abd6-b98ebdf2251e.png)

**Comment by Mailaender** [comment]
This is clearly a mapping problem. What you could do is select another terrain type for the bridge choke points and make it not buildable.

**Comment by nmoskopp** [comment]
> This is clearly a mapping problem. What you could do is select another terrain type for the bridge choke points and make it not buildable.

I did something like that (place rails on bridges) after I realized a human player might do the same.
