### ISSUE TITLE
Map Contribution: “A Tiny Forest”

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#645]
I have made what is possibly the smallest OpenHV 2 player skirmish map that is both fun and playable by the Rogue AI.

Features:

* A direct way towards the enemy base, easily defended.
* Two indirect ways towards the enemy base. Can you defend both?
* Watchtowers that change allegiance on a whim and show enemy resource towers.
* A forest dividing the two bases. Beware: Tanks and APCs can take shortcuts through the woods.
* A whole lot of flammable forest. Only YOU can make sure there is a forest fire when it suits your tactics!

![hv-2022-11-07T154423889Z](https://user-images.githubusercontent.com/22373642/200353094-762ac3fc-e00d-48ca-8996-29cf98153df9.png)

Rename `atinyf.oramap.zip` to `atinyf.oramap` to use the map in the game.

[atinyf.oramap.zip](https://github.com/OpenHV/OpenHV/files/9953296/atinyf.oramap.zip)

**Comment by Mailaender** [comment]
![image](https://user-images.githubusercontent.com/756669/200913128-7e8eb02a-206a-4e3c-ae65-e2788825a46d.png)

The map is easily blocked off, which causes the AI to gets stuck entering the enemy base or even leaving its own:

![image](https://user-images.githubusercontent.com/756669/200913813-53367ddc-ee6e-424d-b12b-2a3eb7e63292.png)

The pathfinder will constantly fail:

![image](https://user-images.githubusercontent.com/756669/200914088-ee67dfb1-5129-46c7-8a9a-de39291a6f35.png)

**Comment by Mailaender** [comment]
The chat says the map is too small in general.

**Comment by nmoskopp** [comment]
I can reproduce the pathfinding issues, they can be quite frustrating. I guess "using tracked vehicles to clear the way through a forest" may be more of a mission-type thing than a gimmick for (small) skirmish maps.

**Comment by Mailaender** [comment]
Uploaded at https://resource.openra.net/maps/48932/
