### ISSUE TITLE
Please remove storage as a prerequisite for bunker and turret

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#646]
Having the requirement to have storage has mainly two effects:

1. Players can not start building bunkers very early to defend against very early rushes. IMO this biases gameplay in favor of rush-friendly build orders even if a player does not want to rush, since having a bunch of pods is the best defense early-on.
2. Players have a hard time to recover from the loss of a storage building, since loss of storage immediately means they can no longer build bunkers or turrets to defend against e.g. a very successful pod drop until they have rebuilt a storage building. Crucially, even a low number of units can harass a base they could not destroy in a way that new defenses are not going to be constructed, leading to unfun drawn-out gameplay.

FYI: Building a storage takes 24 seconds at normal game speed.

**Comment by Dzierzan** [comment]
@Mailaender Remove that prerequisite and let's see how it goes. Keep `module` as prerequisite
