### ISSUE TITLE
Not-yet seen gates are drawn open instead of closed

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#648]
![hv-2022-11-09T170554082Z](https://user-images.githubusercontent.com/22373642/200903781-427b3f10-d12f-4f1d-b4aa-b523016db689.png)

**Comment by nmoskopp** [comment]
I am pretty sure that is it. Why do they start open though and not closed?

**Comment by Mailaender** [comment]
To show off. You can experiment with https://openhv.readthedocs.io/en/latest/release/traits/#hiddenunderfog in the map rules to polish your tiny mini-game.

**Comment by nmoskopp** [comment]
It's not a mini-game, it's a map I made that featues walls. Are you saying I can modify the gate building's starting state for a single map?

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/wiki/Utility has a map resize option.

**Comment by Mailaender** [comment]
No, https://openhv.readthedocs.io/en/latest/release/traits/#gate is currently limited to this behavior.
