### ISSUE TITLE
Wayland is not supported

### ISSUE THREAD

**Issue by Korothi** [OpenHV/OpenHV#649]
Hey.
OpenHV crashes if you force it to use wayland
the solution is to create symlink to SDL2.so to /usr/lib64/libsdl2-2.0.so (then it works)
propably cause is the new SDL2 update.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/20014

**Comment by Mailaender** [comment]
I assume you used the AppImage with bundled SDL 2. Try https://flathub.org/apps/details/io.github.openhv.OpenHV

**Comment by Korothi** [comment]
Flathub one stopped working (crashes with forced wayland) and i have no
idea how to fix that so i got appimage.

sob., 12 lis 2022, 08:00 użytkownik Matthias Mailänder <
***@***.***> napisał:

**Comment by Mailaender** [comment]
https://buildbot.flathub.org/#/builders/40/builds/539/steps/8/logs/stdio

> exec engine/configure-system-libraries.sh'' on host
Searching for Lua 5.1... liblua.so.5.1.5
Searching for SDL2... libSDL2-2.0.so.0
Searching for OpenAL... libopenal.so.1
Searching for FreeType... libfreetype.so.6

In theory, it should use the runtime SDL2 with Wayland support. I have no idea why it still fails.

**Comment by Korothi** [comment]
It works actually if you replace the sdl2.so with latest one.

śr., 16 lis 2022, 22:23 użytkownik Matthias Mailänder <
***@***.***> napisał:

**Comment by Mailaender** [comment]
Then why does it not work with Flatpak? https://github.com/flathub/io.github.openhv.OpenHV/blob/master/io.github.openhv.OpenHV.yaml#L3 should be latest as well.

**Comment by Mailaender** [comment]
Actually, latest https://github.com/libsdl-org/SDL/releases/tag/release-2.24.2 is 16 days old so that might not be included.

**Comment by Korothi** [comment]
Either way, if that thing works and you force wayland (notxwayland) game
works flawlessly (at least on arch with gnome)

czw., 17 lis 2022, 10:25 użytkownik Matthias Mailänder <
***@***.***> napisał:

**Comment by Mailaender** [comment]
Which SDL2 version have you confirmed to work?

**Comment by Korothi** [comment]
![image](https://user-images.githubusercontent.com/88345690/202431835-bb89c228-654e-48af-b981-ce27dff4841e.png)
SDL2-2.24.2-1 from arch repo.
Deleted SDL2.so in extracted appimage in squashfs-root/usr/lib/openhv
linked new via:
ln -s /usr/lib64/libSDL2-2.0.so.0 SDL2.so

**Comment by Korothi** [comment]
my env for wayland:

export MOZ_ENABLE_WAYLAND=1
export MOZ_DISABLE_RDD_SANDBOX=1
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export LIBVA_DRIVER_NAME=nvidia
export QT_WAYLAND_FORCE_DPI=physical
export SDL_DYNAMIC_API=/usr/lib64/libSDL2-2.0.so.0

**Comment by Mailaender** [comment]
Flatpak works, AppImage is still broken.
