### ISSUE TITLE
Recently uploaded maps are not selectable in the dedicated servers

### ISSUE THREAD

**Issue by SeanScherer** [OpenHV/OpenHV#651]
Downloading (manually) either https://resource.openra.net/maps/48842/, https://resource.openra.net/maps/48875 or https://resource.openra.net/maps/48874/ , placing in maps folder and then attempting to select the map in either of the official servers results in the following server response:
"Searching for map on the Resource Center . . . "

The minimap image does not change, and there is no further response or change (I've waited maybe 2-3 minutes).

At least some of the maps that have been uploaded in the past *are* selectable by the process described above.

**Comment by Mailaender** [comment]
You probably uploaded them as map format 12. Try manually setting it to 11. We are currently in between because https://github.com/OpenRA/OpenRA/pull/19891 has been integrated, but the resource center has not been updated yet as there is no stable release.

**Comment by Mailaender** [comment]
https://resource.openra.net/upload/map/ now supports map format 12.

**Comment by Mailaender** [comment]
Not sure why this was reverted @abcdefg30.

**Comment by SeanScherer** [comment]
Perhaps I don't understand the issue, but the maps in mapformat "12" *are* there:

https://resource.openra.net/maps/?format=12&sort_by=latest&with_problems=show&players=

Its just that the problem seems pretty much identical to when I first opened this issue - ie, if you try to run one of them you get either "map not found" or "incompatable version" (can't remember which right now). 
("A Tiny Forest" is what I had tried to get it to run with, btw).

(PS whether uploading works I can't test right now, sorry).

**Comment by abcdefg30** [comment]
> Not sure why this was reverted @abcdefg30.

The changes are still there, but you can't upload maps for the playtest (which doesn't officially exist, since it was never announced).

**Comment by Mailaender** [comment]
It was announced on https://github.com/OpenRA/OpenRA/releases

**Comment by Mailaender** [comment]
https://resource.openra.net/upload/map/ shows a recent version again.

**Comment by SeanScherer** [comment]
I'll test tomorrow evening (when I'm back home).
