### ISSUE TITLE
Map Contribution: A Beautiful Winter

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#653]
“A Beautiful Winter” is a complex 4-player map, featuring:

* Each player's base being attacked by air right at the beginning of the game.
* Small defended creep harvesting bases close to each player's starting base.
* Creeps that defend silver and gold from miners that want to steal the ores.
* 4 drop zones that deliver reinforcements to players that hold them some time.

Notes:
* The map is balanced around thoughtful use of units and support powers.
* Players should assume that most resource spots are at least lightly defended.
* If you send a miner without any escort anywhere, it is definitely your own fault.
* Capturing a drop zone is a really good idea – it pays for itself with the first delivery.
* Spamming units is not likely to work, but is guaranteed to make players run out of money.
* There are limited resources at the starting base by design, but there are enough ores on the map.
* Rogue AI sometimes manages to not defend itself against the initial creep attack. I believe that players that have their main base attacked and are ignoring such an attack for more than two minutes deserve to lose the game. Building a single rocket pod is enough to save the base. Why Rogue AI sometimes does not try to build any pods at all is a mystery to me, but I am pretty sure it happens on other maps as well.

The license for “A Beautiful Winter” is, at your option, either CC-BY-SA 4.0+ or GPL v3+.

![hv-2022-11-19T192033374Z](https://user-images.githubusercontent.com/22373642/202868154-592f3c89-a952-4752-a6ff-72e5cd344813.png)

[abwinter.oramap.zip](https://github.com/OpenHV/OpenHV/files/10047810/abwinter.oramap.zip)

**Comment by Dzierzan** [comment]
I'd give it more details (like stones) and play with lighting as well to match the quality which SiegeSpud provides.

**Comment by nmoskopp** [comment]
> I'd give it more details (like stones) and play with lighting as well to match the quality which SiegeSpud provides.

Is this based on playing the map? I did not include many decorations because stones etc. could affect the path finding.

**Comment by Dzierzan** [comment]
Of course it is not based on playing. There are many stones or decoration tiles which do not block actors.

**Comment by Mailaender** [comment]
The map has the usual huge amount of gameplay problems: you start next to a base of self-healing creep enemies. If the AI survives depends on building placement randomness, as the creeps won't attack otherwise. I fixed up all the linting errors and uploaded it at https://resource.openra.net/maps/48931/

**Comment by nmoskopp** [comment]
@Mailaender you did not only fix linter errors. The map at https://resource.openra.net/maps/48931/ has the following change:

> fixes depleted resources

I had carefully balanced the previous resource distribution with hours of playtesting in OpenHV 20221030.

Based on that, changing it the way you did has the following negative gameplay effects:

* Drop zones, if captured, are easily destroyed by air.
* The communication link is not an important tool anymore.
* Destroying the creep base close to spawn is no longer important.
* It is no longer a useful goal to capture the island resource extractors.
* Players have no pressing need to mine resources further away from spawn.
* Players can expand to resources protected by adjacent creeps much easier.
* Players can overwhelm creeps with numbers, i.e. micro is no longer needed.
* It is both much easier and no longer important to capture any of the drop zones.
* Players can get to each other earlier and much easier, ignoring most of the creeps.
* Players accumulate so much money that attacking resource towers is rarely a viable tactic.

In short, showering players with cash makes the map not a challenge. Additionally, it makes both humans and AI resort to extremely boring strategies like mid-game tank/pod assaults or late-game air unit spam, making creeps and drop zones and communication links and tech reconstructors largely irrelevant. IMO it is precisely the lack of resources close to spawn that made the map work tension-wise.

In light of these downsides to increasing the resources, I wonder why you did it. Was there some pricing change that makes units much more expensive? Or did you try out the map and ran out of money after trying to spam buildings or units in the early game? If so, I would like to see a replay. Or did you just eyeball it?

> If the AI survives depends on building placement randomness, as the creeps won't attack otherwise.

I have never seen creep pods defeat the AI and they are intentionally too weak to do so. Do you have a replay of such a thing occurring?

Btw.: Why did you include depleted ores in the game at all if you seem to reject the tension that comes from running out of resources and needing to expand?

**Comment by nmoskopp** [comment]
@Mailaender I have playtested my low-resource version of the map again just now, using OpenHV 20221119.

I think it plays quite well: Players start to run low on money after 2 or 3 minutes, hopefully motivating them to find more ores outside their base. This duration is long enough to defeat the creeps at spawn (which yields a bit more resources, but fewer of them the longer a player waits) and also long enough to capture a drop zone. By minute 7 or 8, resources at spawn start to run out – but players that have not expanded mining operations by then are probably so bad at OpenHV that they should practice some more on other maps.

The resource limits I put in at spawn seem to work exactly as intended, as neither tank rushes nor airplane spam can be financed well with limited resources. Both of those would make drop zones largely irrelevant.

**Comment by Mailaender** [comment]
Use https://resource.openra.net/upload/map/ to share your maps.

**Comment by nmoskopp** [comment]
I plan to do that in the future, if I make more maps.

Are you going to answer my questions or elaborate on the "huge amount of gameplay problems"?

**Comment by Mailaender** [comment]
I think your map is something else, a new game mode maybe, reminds me of Warcraft III and fighting creeps. However, all those maps were designed with creeps away from the player bases.

**Comment by SeanScherer** [comment]
I've not played the map, but just from your description this reads "custom map" to me (rather than "vanilla OpenHV"). 
So I think even hoping its included in the official release seems a little far fetched to me to be honest...

"what developers consider problematic and why" -> for something like a custom map, I'd argue there is no "right", or "wrong" - just different tastes. I think there are ways of gaining feedback from people that are interested in this kind of map (as I've said before, I don't think Github Issues is a good place to do that though). 

Btw, since you may not have noticed - the issue with maps uploaded at the resource center not being playable in the dedicated servers should be resolved, so there's nothing stopping you going that path anymore!

**Comment by nmoskopp** [comment]
> I think your map is something else, a new game mode maybe, reminds me of Warcraft III and fighting creeps. However, all those maps were designed with creeps away from the player bases.

> I've not played the map, but just from your description this reads "custom map" to me (rather than "vanilla OpenHV").

The map is certainly different from existing maps on purpose. My original intention was to make an OpenHV multiplayer map on which capturing drop zones is actually beneficial and capturing buildings is important to get ahead in the early-game. Additionally, the map punishes mindlessly spamming units.

I do not think it is a different game mode. The reason it may ”feel” different is because I have gone to great length to punish formulaic strategies after I had seen the AI just mass tanks or planes to mow everything down a bit too often.

To make it clear, the following things do not work (or do not work well) intentionally:

* Secure resources using pods (snipers)
* Rush using pods (enemies are too far away)
* Rush using tanks (try it – your money will run out)
* Harass enemies from the air without micro (creep air defenses)
* Sending unprotected miners anywhere (they will be dealt with swiftly)

Players are expected to respond to these circumstances, e.g. not sending unprotected miners out or using the map reveal power to unmask submarines and snipers. I have spent hours on making the map that way.

The map is definitely not much weirder than the forest fire minigame or the tower defense minigame. Both of those are official maps, so I would like to have some clear guidelines about intended gameplay.

**Comment by Mailaender** [comment]
Move the creeps elsewhere and we can include the map.

**Comment by nmoskopp** [comment]
@Mailaender do you mean moving the pod creeps that guard the bases near the spawns? I found that building a single bunker makes it too easy to get rid of them. Also, they were never supposed to attack the players base, so I am moving them further back anyway.

Can the attack plane at spawn stay? It is mostly a gimmick, but as far as I can see a player who loses their main base to it can only achieve that by not building a single rocket pod in over two minutes. Even the AI only rarely seems to achieve this feat.

**Comment by nmoskopp** [comment]
@Dzierzan I have spent a lot of time on adding details. The map looks nicer now. It also plays better, because I made the details meaningful.

Spoiler (rot13 encrypted): Sbe rknzcyr, fcrpvsvp tebhaq qnzntr gvyrf uvag ng zvarf orvat cynprq gurer. Enaqbz fpenc bhg gurer zvtug whfg or n genc gung n favcre frg. Cynarf tbvat nobir gur frn zvtug trg gnetrgrq ol perrc fuvcf. Gurer ner nyfb n ohapu bs fvyyl guvatf, yvxr gur nve onyybba orvat hfrq nf na negvyyrel fcbggre be gur oevqtr gung unf pbafgehpgvba jbexf tbvat ba.

@Mailaender I have moved the creeps further towards the middle and the player spawns a bit back. Also I placed scrap and decorations to ensure the AI does build close to home. Once a player collects the scrap, their base can expand a bit more. I think I will be using this approach more in the future instead of non-buildable tiles. Thanks for insisting on moving the creeps – I realized that giving the player some agency regarding when and how to attack them makes the map more fun. I included a money cube to reward players who defeat the creep base – but IMO it is unlikely to offset their losses entirely.

I made gameplay less linear. It is now both harder and more forgiving. I balanced the resources according to that – a player should now be able to do something stupid like spamming pods and losing all of them when trying to rush the opponent and still be able to come back from it if they change their approach.

Tank spam should still not be viable. Using air units to defeat all creeps may be viable in the mid-to-late game. If OpenHV included an actual air superiority unit, I would have used it in this map to prevent that kind of gameplay. The upside is that players will have a hard time removing the air balloons the creeps need to target their cruise missiles, as those hover in a hard-to-reach places.

So what do you think, can the map “Another Beautiful Winter” be included in OpenHV? If you see any issues linting-wise or with the gameplay, please ask me instead of just including a modified version – I can assure all of you that I put great effort into making this map hard, but fun.

![hv-2022-11-25T203220664Z](https://user-images.githubusercontent.com/22373642/204054888-3f9dd925-438f-4e29-b45d-d16edfffe10b.png)

[abwinter2.oramap.zip](https://github.com/OpenHV/OpenHV/files/10095087/abwinter2.oramap.zip)

**Comment by Mailaender** [comment]
It seems to have exactly the same problems as before: everything that tries to leave the base or is built on the border will get destroyed by the creep fortress. This and the few resources stalls the gameplay.

**Comment by Dzierzan** [comment]
Please, for the next map contributions, use https://resource.openra.net/.
