### ISSUE TITLE
Selling Base displays the wrong pad rollout animation

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#655]
instead of the reversed one.

**Comment by SeanScherer** [comment]
Just tested for this, and the animation plays correctly for Bases that have been build via Outpost (ie its the reverse animation).

Somehow has to do with the base being pre-placed / spawned via the "multiplayer" starting position. (The issue *does* show up for Ice-River as well!).

**Comment by Mailaender** [comment]
I mean the pads.

**Comment by SeanScherer** [comment]
Sorry if I was unclear, I was referring to the pads as well (I think there is no animation for the Base building itself ?)

To sum up: 
* Selling your initial Base will "rollout" the pads (bad), 
* while selling a Base built by an outpost will "rollup" (ie correct animation) the pads.

**Comment by Mailaender** [comment]
If you construct a base with an outpost and sell it, it will show the correct roll-in animation.
