### ISSUE TITLE
Trying to sell a unit on the trade platform sells the trade platform instead

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#665]
To reproduce, click with the selling cursor on a unit on a trade platform.

**Comment by Mailaender** [comment]
This is on purpose. You can't sell units on the trade platform. https://github.com/OpenRA/OpenRA/issues/3798

**Comment by nmoskopp** [comment]
> This is on purpose.

While I understand the linked issue, the description for the trade platform literally says:

> Repairs and **sells vehicles for credits**.
> Allows buying units on the free market.

How could that happen if the feature was “not planned”?
