### ISSUE TITLE
It is not obvious how to build a vertical teleporter

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#667]
The building queue only shows a horizontal teleporter.

**Comment by nmoskopp** [comment]
Is there a hotkey or something to rotate the building?

**Comment by Dzierzan** [comment]
Honestly, televators need to be taken out of skirmish. There's no real usage for them. Maybe for future missions (if anyone makes them) .

**Comment by nmoskopp** [comment]
> Honestly, televators need to be taken out of skirmish. There's no real usage for them.

A televator requires 200 power per building and you need at least two of them.

That alone makes them absolutely useless in terms of investment vs payoff.

**Comment by Mailaender** [comment]
[Documentation](https://github.com/OpenHV/OpenHV/wiki/Hotkeys/_compare/054147f9cd67f0418bc3720c72cdcda953989d0b...fb5351440b5de9e46c9e5a40d0b7d1775c2d8453)
