### ISSUE TITLE
Auto tile turns tile 246 into tile 267 erroneously

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#672]
The right `267` can be replaced with `246` manually, but auto tile will turn it into `267` again.

![Bildschirmfoto_2022-11-25_02-01-11](https://user-images.githubusercontent.com/22373642/203880499-a8710752-318d-4db2-ab14-744a80e9a28f.png)

**Comment by nmoskopp** [comment]
Could it be that the `290` and `291` ice corner tiles are treated as water by auto tile?

**Comment by Mailaender** [comment]
In general, use auto-tile only once and not after polishing for best results.
