### ISSUE TITLE
Rogue AI seems to ignore cubes

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#674]
![hv-2022-11-25T103224832Z](https://user-images.githubusercontent.com/22373642/203967787-ad3fd9ea-4602-4427-ad5c-81067a29fb15.png)

**Comment by Mailaender** [comment]
It checks if hostile are around before deciding it is safe enough to pick up.

**Comment by nmoskopp** [comment]
I guess the “hostile” in this case could be the wall gate of the base shown in the screenshot?

If that is the case, maybe AI should only consider hostile buildings that can attack, not walls.

**Comment by Mailaender** [comment]
There are also hostile pods.

**Comment by nmoskopp** [comment]
> There are also hostile pods.

I noticed, but those hostiles are far away from the cube and the units that could pick the cube up.

I guess the check is really just “are there hostiles nearby” and nothing complex.

I feel a bit silly now.
