### ISSUE TITLE
Pre-placed cubes on a map disappear after a few minutes in the game

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#675]
This makes them mostly useless for me.

**Comment by Mailaender** [comment]
Try disabling https://openhv.readthedocs.io/en/latest/release/traits/#cubespawner

**Comment by nmoskopp** [comment]
The cubes disappear after exactly 2 minutes on fastest speed, and exactly 4 minutes on normal speed.

Enabling or disabling the spawning of additional cubes does not change this as far as I can tell.

I believe either I am misunderstanding something here or the issue should be reopened.

**Comment by GraionDilach** [comment]
Both are wrong, the issue should be transferred to upstream - the Crate trait lacks the Duration tag override from map side. This is  relevant for upstream because Westwood campaign maps relied on this as well.

**Comment by nmoskopp** [comment]
@GraionDilach I love “no one is right, everyone is wrong” answers. Does an upstream issue exist? If it does, which one is it. If it does not, care to open one? Obviously you seem to know more about crates/cubes than me.

**Comment by GraionDilach** [comment]
Due to politics, I am barred to interact with upstream.

**Comment by Mailaender** [comment]
Set
```miniyaml
^Cube:
	Crate:
		Duration: 0
```

in your map.

**Comment by nmoskopp** [comment]
@Mailaender thanks for the workaround. Would that make *all* cubes last forever though or only the pre-placed ones? Also, why would the map editor not set the duration automatically when placing a cube?

**Comment by Mailaender** [comment]
Setting the duration to zero is for pre-placed cubes on campaign maps that don't otherwise spawn cubes.
