### ISSUE TITLE
Map editor does not set selected owner for some actors on placement

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#677]
To make prop 12 part of a creep base I needed to edit it manually.

**Comment by nmoskopp** [comment]
And yes, I do need civilian buildings as part of a faction.

**Comment by Mailaender** [comment]
You are violating the game rules:
https://github.com/OpenHV/OpenHV/blob/7e6938bf60e3a2209e2ae487464f2955f22703ea/mods/hv/rules/defaults.yaml#L589-L590

**Comment by nmoskopp** [comment]
I see. What purpose does that rule serve except aesthetics?

The use case I have is a non-faction building that must be destroyed so enemies/creeps do not get visibility into the area and can attack it from afar. I.e. “destroy the spy tower”.

**Comment by nmoskopp** [comment]
Assigning destructable actors to creeps also is an easy way to let both AI and players know they can be destroyed. For example, I have a bridge that is blocked by decorations that are set to creeps. Rogue AI would not target decorations if they were neutral and thus never unblock the bridge.
