### ISSUE TITLE
Multiple tanks disabling a target continue to fire on it, even if other non-disabled targets are closer

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#682]
This makes it necessary to have absurdly good micro skills to disable units at scale.

Possible workarounds:

* Only target enemies that have not been disabled in the last second or so.
* Only target enemies that are not disabled (unless force-commanded).
* Re-target after each shot, prioritize close or non-disabled enemies.

![hv-2022-11-25T150405193Z](https://user-images.githubusercontent.com/22373642/204024382-2119e3da-64a5-4594-aca8-4ce0b63d0662.png)

**Comment by Mailaender** [comment]
The noncontinuous fire has downsides in 1v1 situation.
