### ISSUE TITLE
Main base constructs vehicles, but should not

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#684]
I pre-placed two vehicle factories in the map in the screenshot. All tanks came out of the main base.

Suggestion: Separate the build queue for vehicles constructed by the main base from the queue of the vehicles constructed by the vehicle factories. The interface has enough space for this.

![hv-2022-11-26T141330676Z](https://user-images.githubusercontent.com/22373642/204093218-a1f49c76-24cb-4094-8492-4ac9bcbb299e.png)

**Comment by nmoskopp** [comment]
Vehicles come out of the respective factory when it is set as the primary factory.

Vehicles come out again of the main base when the primary factory is unset again afterwards.

**Comment by SeanScherer** [comment]
I was going to say, you can set the/a vehicle factory as the primary via map-lua (iirc) if that's whats important to you.

**Comment by nmoskopp** [comment]
> I was going to say, you can set the/a vehicle factory as the primary via map-lua (iirc) if that's whats important to you.

True, but that would only be a workaround. The real issue here is that somehow the shared building queue logic is messing up what type of units can be produced where. It should not be the responsibility of players or map designers to make sure that the engine keeps track of where vehicles come out.

**Comment by SeanScherer** [comment]
I was trying to point out a solution for you just now - but maybe I shouldn't bother, considering I'm not getting replies to my email either anymore :P.

**Comment by amoskopp** [comment]
> I was trying to point out a solution for you just now - but maybe I shouldn't bother, considering I'm not getting replies to my email either anymore :P.

I am sorry. Please resend whatever email you sent before.
