### ISSUE TITLE
Technician rushes are too easy and unfun

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#689]
A rush containing a single technician (and possibly some pods to guard) can quickly capture a  storage building or a resource tower or some other important early-game building. This can make make it almost impossible for an opponent to recover. IMO the momentum this provides the attacker is too big for good balance. It is also too swingy for my taste: A technician either steals one or more buildings or it dies without accomplishing anything. Rushing with 5 machine-gun pods (same cost: 500$) can provide much less of an advantage, but probably does some damage unless the first building encountered is an enemy bunker.

Suggestion: Require a storage building in addition to the pod assembly to build technicians. Such a change would barely change other parts of the gameplay that involves technicians, but would make it much harder to technician rush. For maps where technicians are supposed to capture money generators or other buildings, it would also create more tension, as armed pods having a 24 second head start (build time of storage building) makes it more likely that an escort for a technician makes sense.

**Edit:** My suggestion imitates what OpenRA+ does with the Red Alert engineer prerequisites.

**Comment by Mailaender** [comment]
It is already balanced in a way that the capture is not instant.

**Comment by nmoskopp** [comment]
> It is already balanced in a way that the capture is not instant.

I believe you have misunderstood my point. IMO there exists no balancing problem with the technicians capturing mechanic here. The issue is rather that rushing with a technician on a small map is an almost guaranteed win against a player who has not protected access to their base using pods or bunkers.

I am often able to technician rush the AI on “business as usual” and anyone else can too with minimal skill – but IMO this is not the fault of the AI. The problem is more that a powerful unit is available early only for a pod-assembly-before-storage build order and the defense against it is too. This creates an incentive in favor of pod-assembly-first build orders even for players who do not rush, which inhibits player choice.

Many units would have similar effects if they could be produced right away – bomber pods for example. Such a thing does not make a unit inherently unbalanced. It just illustrates why the game has tech levels and prerequisites for units.

Requiring a storage to produce an engineer would delay the technician enough to make them not the first choice for rushing, as a player would need to have both storage and pod assembly. The 24 seconds of build time for the storage plus 12 seconds of build time for a technician would be the same time it takes to build 12 machine gun pods or 6 rocket pods. Right now though a rush with a technician is the time equivalent of rushing with four machine gun pods, two machine gun pods and a rocket pod, or two rocket pods – all of which are much less powerful than a single technician in the early game.

**Comment by Mailaender** [comment]
I think the only logical pre-requisite would be the repair pad and that is too late game.

**Comment by nmoskopp** [comment]
> I think the only logical pre-requisite would be the repair pad and that is too late game.

Why? The storage is the first building that delays production of a technician just  enough to make other rush types useful on small maps and allow defense against technician rushes. So what makes storage *not* the only logical pre-requisite? And why would it be the repair pad and not any other building?
