### ISSUE TITLE
Technicians  are swingy (either too powerful or useless)

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#690]
Suggestions:

1. To make technicians more useful, let them repair pods in addition to their current ability, like the OpenRA medic does. Such a change would encourage the use of technicians even far from enemy buildings, creating more tension in gameplay.
2. To make technicians less swingy, let them capture neutral buildings without entering them afterwards, but capture enemy buildings with entering them afterwards. This should largely preserve gameplay on maps with multiple neutral buildings. It would also create beneficial tension – players would have to decide which building is important enough to sacrifice a technician. This part of the suggestion imitates what OpenRA+ does with the Red Alert engineer.
3. To make the new medic-engineer technicians easier to afford , lower the price to 250$ or so.

**Comment by Mailaender** [comment]
We already have a repair tank that can repair all vehicles including pods so a medic pod adds redundancy.
