### ISSUE TITLE
Remove repetitive clicking at skirmish match start

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#692]
The first ten seconds or so of a skirmish match are always the same: Players select their main base or building queue, build a power plant, survey the visible area and place the power plant at a suitable location. Doing this again and again feels repetitive, tiring and unfun, as players have no choice but to do this if they want to build anything except a builder (which is not a building, but can deploy into an outpost).

Suggestions:

1. Let the main base provide 50 power – enough for a single pod assembly and storage.
2. Remove the prerequisite for a power plant from pod assemblies and storage.

As with some of my other recent suggestions, this is inspired by OpenRA+.

**Comment by Dzierzan** [comment]
All RTS games start like that. If anything, I'd add additional options for extra units at the beginning like:

1) Extra miners
2) Extra pods
3) Miners and pods

And so on. You get the idea.

**Comment by nmoskopp** [comment]
> All RTS games start like that. If anything,

RTS games inspired by early Westwood titles (Dune 2, Command & Conquer) do this.

Other RTS game lineages provide user choice right away.

Examples for RTS games with a different lineage:

1. Homeworld & Deserts of Kharak: Players start with a mobile base that can produce units.
2. Warzone 2100: Only resource extractor buildings actually need a working power plant. In skirmish games an option exists to start with fully outfitted bases at several tech levels, as the campaign-focused tech tree is huge.
3. Earth 2150: The Lunar Corporation uses solar panels and batteries (the game has a day-night cycle) and a main base (heavily armed production building) that can operate even without power (IIRC). I remember that the tech tree thing was possible here as well, but maybe that was a mod I used.
4. Liberation Circuit: Players start with an immobile base that can produce units. The starting unit can be freely customized before the game, as long as it does not exceed the initial resources. Even build orders can be scripted, so it is possible to build a Von Neumann probe builder that will seek out resources and construct a mining base there.
5. Mindustry: Not all buildings need power. but advanced defense and production buildings do. Depending on the map and the available resources and the planet the player plays on, there are a bunch of different ways to get that power. Solar panels, batteries, power plants that can only be placed on thermal vents, power plants that consume resources, power plants consume different resources, power plants that produce waste, nuclear power plants that have to be cooled down continuously or they explode… the game has it all.

**Comment by nmoskopp** [comment]
> I'd add additional options for extra units at the beginning

You might be thinking that the advantage given is symmetric … but having extra pods at the beginning of the game without having appropriate base defenses is likely to make rushing more viable.

Needing to build one less power on the other hand makes rushing less viable, as bunkers can show up earlier and the defending player has only one building to protect that they protect anyway (the main base).

**Comment by Dzierzan** [comment]
OpenHV is meant to be Westwood alike game with libre assets. Hence why I prefer it to stay as it is now.

> You might be thinking that the advantage given is symmetric … but having extra pods at the beginning of the game without having appropriate base defenses is likely to make rushing more viable.

Hence those are meant to be extra options for fun I would say.

**Comment by Mailaender** [comment]
6. Tiberian Twilight: Players start with a mobile base that can produce units.

Sometimes you streamline too much and everybody hates your game.

**Comment by nmoskopp** [comment]
> OpenHV is meant to be Westwood alike game with libre assets.

Please stop with the rhetorical tricks. I was suggesting to remove useless busywork with an approach that gives the player more agency and makes rushing a bit riskier. The TD and RA implementations of OpenRA have changed stuff that was deemed unfun and the discussion here was about fun and not conservative game choices.

As I see it, every “no one wants this” followed by ”well, no one who matters (to me) wants this” is a rhetorical trick to disguise the unwillingness or inability to address the actual point.

The [Hard Vacuum design blog post](https://lostgarden.home.blog/2005/03/27/game-post-mortem-hard-vacuum/) contains the following:

> Games like C&C and Warcraft solidified the major conventions of RTS games. Unfortunately, in the game industry, massive success breeds design stagnation. Once a successful formula for creating a RTS was discovered, gamer designer copy the basics and then focus on polishing the basic formula. […]
> 
> Pick up and play an ancient copy of a game that fathered a genre. The further back you can go, the better. Clear your mind of all expectations and knowledge of what the genre evolved into. That cool thing that Half Life did with conversations. Forget it.
> 
> Now reinvent the genre. What are the core primitive concepts and where can you take them that would result in addictive player experiences? You have the opportunity to reinvent an entire decade of evolutionary game design in your head. Chances are you will spawn a few original ideas.

**Comment by nmoskopp** [comment]
> 6. Tiberian Twilight: Players start with a mobile base that can produce units.
> 
> 
> Sometimes you streamline too much and everybody hates your game.

Given that Homeworld-style games (Homeworld / HouseGlobe / Deserth of Kharak / Liberation Circuit) have managed to to pull this off and are actually liked, what do you think TIberian Twilight did wrong?

(I have never played Tiberian Twilight.)

**Comment by Mailaender** [comment]
See https://www.metacritic.com/game/pc/command-conquer-4-tiberian-twilight

**Comment by nmoskopp** [comment]
>> You might be thinking that the advantage given is symmetric … but having extra pods at the beginning of the game without having appropriate base defenses is likely to make rushing more viable.

> Hence those are meant to be extra options for fun I would say.

I do not think it would make the base building part of the game any more fun, but I would definitely like a game option to start with a reasonably sized army of my faction and no base. I guess the drop pod logic already contains some placement code that could be re-used, am I correct?

**Comment by Mailaender** [comment]
This is not a forum nor a chat room.
