### ISSUE TITLE
Make resource transporters and builders auto-carryable

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#698]
This would allow players to use transport aircraft to lessen the danger to their supply lines or bypass obstacles easier and allow playable maps with ores on small islands where a base is not useful or possible for the mid-to-late-game.

Could toggling between auto and manual mode for an AutoCarryall be done using deployment?

**Comment by Mailaender** [comment]
No, that won't work as right click or <kbd>F</kbd> is already used to land and exit.
