### ISSUE TITLE
Deploy submarines to bring them to the surface for tradeoffs in speed and visibility

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#699]
The following traits make a submarine that can be deployed to surface. When surfaced it loses its cloak, but can see further and is 1.5 times as fast. I believe this approach needs some polish, but this mechanic looks and plays well.

```miniyaml
^Submarine:
	Inherits: ^Ship
	RevealsShroud:
		Range: 7c0
		RequiresCondition: !underwater
		RevealGeneratedShroud: false
	RevealsShroud@Hacked:
		Range: 4c0
		RequiresCondition: !underwater
	RevealsShroud@Underwater:
		Range: 3c0
		RequiresCondition: underwater
	GrantConditionOnDeploy:
		DeployedCondition: deployed
	SpeedMultiplier@Surfaced:
		Modifier: 150
		RequiresCondition: deployed
	Cloak:
		DetectionTypes: Underwater
		InitialDelay: 0
		CloakDelay: 100
		CloakedCondition: underwater
		CloakSound: submarine_out_szegvari.wav
		UncloakSound: submarine_in_szegvari.wav
		Palette: shadow
		PauseOnCondition: cloak-force-disabled
		RequiresCondition: !deployed
	GrantConditionOnDamageState@Uncloak:
		Condition: cloak-force-disabled
		ValidDamageStates: Critical, Heavy
	LeavesTrails:
		RequiresCondition: cloak-force-disabled
	DetectCloaked:
		CloakTypes: Underwater
		Range: 4c0
	RenderDetectionCircle:
```

**Comment by Mailaender** [comment]
[Except that submarines are faster underwater.](https://navalpost.com/submarine-cavitation-drag-underwater-speed/) It also requires a lot of micro just to fight some boats, which seems unfair.

**Comment by nmoskopp** [comment]
> [Except that submarines are faster underwater.](https://navalpost.com/submarine-cavitation-drag-underwater-speed/)

The tradeoff could also be speed underwater vs visibility on surface.

> It also requires a lot of micro just to fight some boats, which seems unfair.

How does giving an option to deactivate a cloak for some bonus *require* micro in a fight?

**Comment by Mailaender** [comment]
Because you reduced the vision range. You have to right-click to make the unit not useless. Otherwise, I like the change.
