### ISSUE TITLE
Limit ammunition for heavy aircraft

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#701]
Currently, banshees and speeders have bottomless missile magazines. Both provide a simple and boring way to steamroll units and buildings, even if those are protected by anti-air support. In several other OpenRA games heavy aircraft have limited ammunition and need to either reload or wait, which increases tension.

Suggestion: Give banshees and speeders a limited amount of missiles so they can not loiter in an area forever to make it off-limits to the opponent. Let them reload at the aircraft production building.

**Comment by nmoskopp** [comment]
Heavy aircraft fire shots in salvos of two or three shots. Because of this,  `PLANE2` needs twice as much ammo as it has ammo pips and `BANSHEE` needs thrice as much ammo as it has ammo pips.

**Comment by nmoskopp** [comment]
@Mailaender how did you come up with the reload times and ammo counts used in https://github.com/OpenHV/OpenHV/commit/574b97d9720d4fb31dd2cc4d4a36dbb1902a1547 ? If I am not mistaken, non-copter units reload so fast that it barely has an impact (and for copter units it has a really small impact). 

Speeders in particular seem to reload as fast as they fire, so the change seems purely decorative to me.

Also, as I pointed out above:

> BANSHEE needs thrice as much ammo as it has ammo pips

**Comment by Mailaender** [comment]
I eyeballed it.

**Comment by nmoskopp** [comment]
@Mailaender I see. I suggest you try it out for yourself then. I was not able to make a speeder deplete its ammunition against a stationary enemy when I tried – it fires once, turns around and has reloaded by the time it fires again.

**Comment by nmoskopp** [comment]
I believe this issue should not have been closed, as https://github.com/OpenHV/OpenHV/commit/574b97d9720d4fb31dd2cc4d4a36dbb1902a1547 did not seem to achieve its intended purpose.

For aircraft that reload faster or about as fast as they can fire, the “steamrolling” problem still exists – they essentially have infinite ammunition.

I have two suggestions:

1. Give aircraft more ammo, but require reloading at a base.
2. Keep the ammo, but increase the reloading times a lot.

Any of those would work fine for all aircraft. For immersion though, I suggest to split those approaches either between low-tier air units (reload timer) and high-tier air units (return to base) or between factions to meaningfully differentiate the gameplay.

**Comment by Mailaender** [comment]
There was https://github.com/OpenHV/OpenHV/commit/9d44a0e6ffad293fda631ab9af0c922fa8c6c28c by @Dzierzan which increased the ammo capacity by a huge margin. Please send a pull request if you come with better stats.
