### ISSUE TITLE
Let player start with units only, disable “short game” for that case

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#702]
I inserted the following in `world.yaml`, but everyone immediately loses if “short game” is checked.
```miniyaml
	StartingUnits@BuilderYI:
		Class: builder
		ClassName: Builder only
		Factions: yi
		BaseActor: builder
	StartingUnits@BuilderSC:
		Class: builder
		ClassName: Builder only
		Factions: sc
		BaseActor: builder
	StartingUnits@BuilderScoutYI:
		Class: builderscout
		ClassName: Builder + Scout
		Factions: yi
		BaseActor: builder
		SupportActors: saucer
	StartingUnits@BuilderScoutSC:
		Class: builderscout
		ClassName: Builder + Scout
		Factions: sc
		BaseActor: builder
		SupportActors: balloon
```
I know you can disable “short game“ per map – but is it possible to disable it depending on the starting units chosen?

**Comment by Mailaender** [comment]
The game rules are not persisted across clients if you change yours. I don't understand what you are trying to achieve, but starting the game without buildings without changing the victory conditions is expected to behave like this.
