### ISSUE TITLE
Hacker tank information leak

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#703]
An opposing player can find out where shroud is regenerated and infer useful information from that about movements of the hacker tank (and, likely, every army that a hacker tank is part of). A fix for that is to allow players to toggle the shroud generation manually via deployment. I therefore propose the following:

```miniyaml
TANK8:
	Inherits: ^TrackedVehicle
	Inherits@Selection: ^SelectableSupportUnit
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 200
		Prerequisites: ~factory.yi, radar, tradplat
		Description: Disrupts satellite video links\nand obscures the battlefield (toggleable).\n  Jams incoming missiles\n  Unarmed
	Valued:
		Cost: 400
	Tooltip:
		Name: Hacker Tank
	UpdatesPlayerStatistics:
		AddToArmyValue: true
	Health:
		HP: 10000
	Armor:
		Type: Heavy
	Mobile:
		Speed: 150
	RevealsShroud:
		Range: 7c0
		MinRange: 3c0
	CreatesShroud:
		Range: 9c0
		RequiresCondition: !deployed
	RevealsShroud@Hacked:
		Range: 3c0
	WithRangeCircle:
		Color: 00080808
		Range: 9c0
		RequiresCondition: !deployed
	DetectCloaked:
		Range: 2c0
	GrantConditionOnDeploy:
		DeployedCondition: deployed
```

**Comment by Mailaender** [comment]
I see that you are using `WithRangeCircle` because of an engine limitation which I decided to fix in https://github.com/OpenRA/OpenRA/pull/20497.

**Comment by nmoskopp** [comment]
Is this issue blocked by https://github.com/OpenRA/OpenRA/pull/20497?
