### ISSUE TITLE
Unload transport tank passengers on death

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#705]
A transport tank can hold a lot of passengers, but all of them are lost if a player does not manage to hit the “unload” button in time when the transport tank is at low health. Setting `EjectOnDeath` for the `Cargo` trait should fix this.

**Comment by Mailaender** [comment]
There were also known problems:
* https://github.com/OpenRA/OpenRA/issues/16353
* https://github.com/OpenRA/OpenRA/issues/17863
