### ISSUE TITLE
Sonar pulse support power

### ISSUE THREAD

**Issue by nmoskopp** [OpenHV/OpenHV#706]
Suggestion: A support power to reveal all submarines and, if they are added at some point, sea mines in an area for a short time – i.e. a camera to detect cloaked units in water. Prerequisites could be harbor + radar.

**Comment by Mailaender** [comment]
We already have
https://github.com/OpenHV/OpenHV/blob/9d44a0e6ffad293fda631ab9af0c922fa8c6c28c/mods/hv/rules/bonus.yaml#L90-L100

**Comment by nmoskopp** [comment]
Indeed – but it is usually not available, as it requires a single building that can not be built by any faction and is not present on most maps IIRC.

**Comment by Dzierzan** [comment]
You've got scouts boats for that.

**Comment by nmoskopp** [comment]
> You've got scouts boats for that.

Scout boats do not create tension in the same way, as the enemy may know that you know where their units are upon seeing a scout boat and is likely to be audibly alerted to your presence if it comes to a shooting match.

Camping using hidden units feels way more boring if there is no way to uncloak them easily except for running into them.
