### ISSUE TITLE
Bots don't know how to transport units

### ISSUE THREAD

**Issue by Mailaender** [OpenHV/OpenHV#721]
Neither cargo nor carryall.

**Comment by dnqbob** [comment]
I have a solution to cargo, but only for loading. [LoadCargoBotModule.cs](https://github.com/MustaphaTR/OpenRA/blob/rv-engine/OpenRA.Mods.AS/Traits/BotModules/LoadCargoBotModule.cs)

I strongly suggest it used with the  [AutoDeployer.cs](https://github.com/MustaphaTR/OpenRA/blob/rv-engine/OpenRA.Mods.AS/Traits/AutoDeployer.cs) and [AutoDeployManager.cs](https://github.com/MustaphaTR/OpenRA/blob/rv-engine/OpenRA.Mods.AS/Traits/Player/AutoDeployManager.cs):

You can see the testcase in https://github.com/ABrandau/Shattered-Paradise-SDK

**Comment by dnqbob** [comment]
I remove most of preloaded units for AI after using those.
