### ISSUE TITLE
macos dmg missing OpenRA.Mods.HV.dll

### ISSUE THREAD

**Issue by zielu** [OpenHV/OpenHV#729]
Hello,
when trying to run the game I was getting exception about missing OpenRA.Mods.HV.dll file.
After manually copying OpenRA.Mods.HV.dll (and pdb) from winportable.zip to /Applications/OpenHV.app/Contents/MacOS/x86_64/ game started normally.

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/actions/runs/4336616450/jobs/7572036121 indicates it might be https://steven-giesel.com/blogPost/554ba273-9594-4d55-aac2-1366e28954b3

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/commit/f287948059b23ea0cd5f4db9ec1136df97e2bc00

**Comment by Mailaender** [comment]
Simply rebuilt it https://github.com/OpenHV/OpenHV/actions/runs/4336616450/jobs/7748622432 Now the error is just a warning. Can you test again?

**Comment by zielu** [comment]
All good now, thx !
