### ISSUE TITLE
Failed to build, cannot remove ./engine/bin/*.so when using Mono

### ISSUE THREAD

**Issue by EchedeyLR** [OpenHV/OpenHV#741]
It seems that current version doesn't build properly:
```
#17 18.27   OpenRA.Platforms.Default -> /srv/openhv/application/engine/bin/OpenRA.Platforms.Default.dll
#17 18.51   OpenRA.Launcher -> /srv/openhv/application/engine/bin/OpenRA.dll
liblua5.1.so.0
#17 18.69 Searching for SDL2... libSDL2-2.0.so.0
#17 18.69 Searching for OpenAL... libopenal.so.1
#17 18.70 Searching for FreeType... libfreetype.so.6
#17 18.71 Downloading IP2Location GeoIP database.
#17 19.58 make[1]: Leaving directory '/srv/openhv/application/engine'
#17 19.58 rm: cannot remove './engine/bin/*.so': No such file or directory
```

The error, as can be seen, happen while trying to remove engine files that doesn't exist. I guess the issue here is that these rules were changed manually and never checked.

This doesn't happen in the previous version.

**Comment by EchedeyLR** [comment]
The issue is at https://github.com/OpenHV/OpenHV/blob/master/Makefile#L144.

I guess the main change here is trying to remove `dll` files instead of `so`. I need to check when this bug was introduced in the build system.

**Comment by EchedeyLR** [comment]
So, the specific commit was 3 weeks ago and seems to be https://github.com/OpenHV/OpenHV/commit/f5eee9cfe55b266d1ccd79b01eb0381c05e8d4a5

**Comment by Mailaender** [comment]
Can you supply your build command?

Because

* https://aur.archlinux.org/packages/openhv
* https://github.com/flathub/io.github.openhv.OpenHV
* https://github.com/OpenHV/Server

all build fine.

**Comment by EchedeyLR** [comment]
The problem happens at adding the "unix-generic" option.

**Comment by EchedeyLR** [comment]
Mmmm, is not the script "configure system libraries" needed even with Mono?

**Comment by EchedeyLR** [comment]
Also, I apologize for not checking into this. Got the week busy and missed it because of a certification exam too.

Aaaaaaag.

**Comment by Mailaender** [comment]
I think you are right. My solution isn't optimal. Those linked `*.so` files shouldn't require a deletion in the first place.
