### ISSUE TITLE
Make Tier 3 units bigger

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#750]
Make Tier 3 units bigger to accent their presence on the battlefield. High tech units should feel more substantial with their appearance.

**Comment by Dzierzan** [comment]
I could improve lightning tank artwork, feels a bit skinny for sure. For railgun tank? Feels OK to me.

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/pull/1064
