### ISSUE TITLE
Separate Main Base and Factory queues

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#752]
Producing units in the Main Base doesn't allow simultaneous production in the factory and vice versa. This is counterintuitive because these are separate buildings.

Suggestion: add an icon to units produced in the Main Base similar to pod weapons to disntinguish them from regular factory units.

![image](https://github.com/OpenHV/OpenHV/assets/130343373/35710e99-84ac-4f3b-8507-af77d442605d)

**Comment by Dzierzan** [comment]
Well, I could do it, it's not that hard really. But this means making extra button for that.
