### ISSUE TITLE
Add Supply Truck unit

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#753]
Add Supply Truck unit produced at the Main Base to enable aiding ally with money transfer.

**Comment by Dzierzan** [comment]
Does OpenRA support this? If not, is it needed? Because that means creating both code and art.

**Comment by Mailaender** [comment]
See [vehicles.yaml](https://github.com/OpenRA/OpenRA/blob/c609c4af1490b0277418ffbcc212405e0ccd6b92/mods/ra/rules/vehicles.yaml#L555-L579).

**Comment by Mailaender** [comment]
Our mining trucks are basically that. I might make more sense to allow them to redirect.

**Comment by Mailaender** [comment]
Turns out you can already send them to friendly storage which makes this redundant.
