### ISSUE TITLE
AI air units were attacking my air units without causing any damage

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#756]
I just played a match where I rushed air with helicopters, and the AI's air units were shooting them, but no damage was being dealt. I attached a replay for verification.

[Air attack bug? hv-2023-07-29T184847Z.orarep.zip](https://github.com/OpenHV/OpenHV/files/12207915/Air.attack.bug.hv-2023-07-29T184847Z.orarep.zip)

**Comment by Mailaender** [comment]
I have seen the AI do that, but I can't find a flaw in the game rules.
