### ISSUE TITLE
Miner cannot deploy when a unit is standing next to resource

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#774]
When a unit is standing on the right side of the resource miner won't deploy. Colliding unit should be forced to move or be destroyed.

![image](https://github.com/OpenHV/OpenHV/assets/130343373/6fbcf7db-3674-4802-95d9-39ae0a056518)

**Comment by Mailaender** [comment]
Submitted upstream https://github.com/OpenRA/OpenRA/pull/21016
