### ISSUE TITLE
Synapol Generator does not show up in Map Editor

### ISSUE THREAD

**Issue by SiegeSpud** [OpenHV/OpenHV#786]
Synapol Generator does not show up in Map Editor. The only Generator listed belongs to YI.

**Comment by JovialFeline** [comment]
It's not the most intuitive thing, the Synapol variant should show if an owner with that faction is selected. The same is true for some other buildings like the Storage and Tech Center.
![OpenHV_SynapolVar](https://github.com/OpenHV/OpenHV/assets/4985264/a7b7f966-6966-447e-b574-891b6f875d03)

**Comment by Dzierzan** [comment]
Generator uses `RenderSprites` trait. By default it uses YI variant. SC one will be only displayed if you indeed select Synapol faction in map editor.

In order to display both, SC Generator would have to an actual 2nd building actor.
