### ISSUE TITLE
Air is too dominant

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#824]
Air is too dominant during matches: the Starports cost too low power compared to other military production buildings.

What about changing Starport power requirement to 30, Vehicle Factory to 120 and Harbor to 90?

**Comment by Rampoina** [comment]
30 still seems to be a bit low. The main point is to try to make rushing air less safe so that it's not the prevalent option. With 30 you only have to make one extra power plant. @WilliamWeberBerrutti and I still have to test this in real matches.
