### ISSUE TITLE
Fire Watch mission is broken

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#869]
- You cannot build any units, as you've got no money.
- Fire Fighter Tank's icon doesn't match the used sprites, it's missing the barrel.

**Comment by JovialFeline** [comment]
https://github.com/OpenHV/OpenHV/commit/cddd6802d77f08911ad00090e0368ae61c694acc understandably sets the default money for missions to 0 but Fire Watch never had its start cash specified. Other missions don't seem to be affected.

The sprite bit is well outside my wheelhouse.

**Comment by Dzierzan** [comment]
The 2nd issue was probably created when Matze made Money Tank actor thingy. It's easy to fix it, though.
