### ISSUE TITLE
Ore Smelters cannot be captured once powered off (maybe this happens with other buildings too)

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#874]
I couldn't identify the condition while playing, but I was unable to capture some powered off Ore Smelters with my Technicians. I attached the replay for evidence (it's near the end when I decided to capture buildings, when attacking the AI player at the North-East).

[Ore_Smelter_Capture_Bug_hv-2023-12-02T185510Z.orarep.zip](https://github.com/OpenHV/OpenHV/files/13537151/Ore_Smelter_Capture_Bug_hv-2023-12-02T185510Z.orarep.zip)

**Comment by SiegeSpud** [comment]
Should they even be capturable? It makes more sense to disable capturability for this building.

**Comment by Mailaender** [comment]
I can't reproduce this. They get captured just fine in my tests.
![image](https://github.com/OpenHV/OpenHV/assets/756669/7fe80514-09f0-4276-9e86-55a672c2b3a9)

**Comment by WilliamWeberBerrutti** [comment]
That's strange. I'm also not being able to reproduce on my dev branch. Maybe it was fixed somehow?
