### ISSUE TITLE
Resource Extractors seem too powerful compared to Mining Towers

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#890]
This image shows the earnings when I captured 2 Resource Extractors. As you can see, my earnings were higher, but by a large margin. Resource Extractors should generate less income.

![clipboard](https://github.com/OpenHV/OpenHV/assets/7718402/01c9b2a4-85b8-4fb9-bdaf-671fe85c47a5)

**Comment by Dzierzan** [comment]
You can either change the amount of cash or time interval. Choose one and make a PR.
