### ISSUE TITLE
Planes won't attack targets if approaching from an Angle

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#906]
If you send 1 plane attack a 3x2 building like Main Base, if it approaches from the North-Eastern corner, the plane won't attack.

**Comment by Mailaender** [comment]
Try increasing https://github.com/OpenHV/OpenHV/blob/4799dbbf7b6980e11180a76127a652551a3061d0/mods/hv/rules/aircraft.yaml#L34
https://openhv.readthedocs.io/en/latest/release/traits/#attackfrontal

**Comment by WilliamWeberBerrutti** [comment]
I increased to 360 and it seems it's having consistant attacks from all angles. Will change it on BalanceAir branch.
