### ISSUE TITLE
Add Friend and Foe Colors

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#935]
In AoE2, there's a hotkey that, after pressed, colors the player as blue, allies as yellow, and enemies as red. That makes it easier for the player to identify who's ally and who's enemy, specially in matches where it's difficult to identify it (like, for instance, 4vs4, or enemies and allies with similar colors). Maybe this could be interesting to be added in OpenHV?

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/2462

**Comment by Mailaender** [comment]
See the [FAQ](https://github.com/OpenHV/OpenHV/wiki/FAQ#is-there-a-color-blind-mode) on how to customize the colors.
