### ISSUE TITLE
Crash right after landing a droppod near map's border

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#937]
I forgot to use `make version`, but it's the latest development version from `main`, which is this commit: https://github.com/OpenHV/OpenHV/commit/d927359f8cce7d24200700efcb7df39bc605ce70.

[exception-2024-02-26T190515Z.log](https://github.com/OpenHV/OpenHV/files/14409706/exception-2024-02-26T190515Z.log)

**Comment by Mailaender** [comment]
I can't reproduce it. Can you mark the spot on the map where it crashes?

**Comment by WilliamWeberBerrutti** [comment]
It seems I also can't reproduce it. Iirc it was on this border and had a mining tower or two in Diminishing Returns. I should've sent the replay too, apologies!

![Screenshot_20240326_201213](https://github.com/OpenHV/OpenHV/assets/7718402/ad625eb6-1d01-4192-b6f5-7ee6d015ff83)

**Comment by WilliamWeberBerrutti** [comment]
It seems I can't reproduce it too. I forgot where was the spot (I should've sent the replay, my apologies!).

Maybe the droppods didn't cause the crash, but the land transport units, which was corrected on https://github.com/OpenHV/OpenHV/issues/889, but it was just a coincidence it happened at the exact moment I used the droppods.

**Comment by Mailaender** [comment]
Yes, these pathfinder related crashes require the replay.
