### ISSUE TITLE
It's possible to use DropPods on the water, wasting it

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#944]

**Comment by GraionDilach** [comment]
What would the expectation be here? Preventing the player to activate the power on water or creating a transport of some kind which would contain the pod until it reaches the shore and then automatically evacuate it?

**Comment by WilliamWeberBerrutti** [comment]
Thinking on balancing, I think preventing the player to activate the power on water should be better, since on other liquids the player can't use this power, iirc.

**Comment by Mailaender** [comment]
Similar to https://github.com/OpenRA/OpenRA/issues/13422
