### ISSUE TITLE
Paradropping tanks is bugged.

### ISSUE THREAD

**Issue by Dzierzan** [OpenHV/OpenHV#945]
![paradrop](https://github.com/OpenHV/OpenHV/assets/17529329/98bb9ecf-88b8-4ab9-b1f0-8bea6cc2a87c)

Tested in the latest master commit 29f22410b3039d2f91c2d48de88d27cd98f188ed

**Comment by Mailaender** [comment]
Can't reproduce. I see a parachute.

**Comment by Dzierzan** [comment]
Looks like recent engine update fixed it. At least I confirm it no longer happens in the latest dev commit.
