### ISSUE TITLE
Land units can walk on Lava

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#953]
This happened on map Disruptive Innovation.

![Screenshot_20240412_180958](https://github.com/OpenHV/OpenHV/assets/7718402/73334c2d-4307-433f-bbc6-fbfd3985c077)

**Comment by Mailaender** [comment]
It is a regression from https://github.com/OpenHV/OpenHV/commit/1f11225192965d1fbf93432f50e6991d1d4a89a1.
