### ISSUE TITLE
Crash after using many Hacker Tanks

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [OpenHV/OpenHV#973]
My game just crashed. I was playing on the latest commit dev version. I was spamming Hacker Tanks, and in the moment I ordered an enemy Resource Transporter to move with right click it crashed.

[hv-2024-05-28T224810Z.orarep.zip](https://github.com/OpenHV/OpenHV/files/15476762/hv-2024-05-28T224810Z.orarep.zip)
[exception-2024-05-28T230040Z.log](https://github.com/OpenHV/OpenHV/files/15476764/exception-2024-05-28T230040Z.log)

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/21438
